thrumdev/nomt

- core/src/page.rs
- core/src/proof.rs
This addresses review on #29 that the `Page<'a>` struct having a lifetime is too unwieldy.
There are 4 approaches I considered to working around this:
1. Change `Page` to own the data. This is a non-starter as it inhibits any kind of intelligent arena allocation.
2. Change `PageSet` to be generic over a `Page: Borrow<RawPage>`. This introduces a generic which is somewhat unwieldy but also allows high flexibility. This approach is taken in this PR.
3. Make `PageSet` a trait rather than a struct. I actually quite like this approach, as it pushes indexing and managing tree relationships between pages up the stack while limiting the amount of generics: just write `impl PageSet` in most places and you're good to go. I may revisit and do this instead later. …
> refactor: enable 'static pageset

- core/src/page.rs
- core/src/proof.rs
This is an alternative approach to making trie algorithms generic over where pages are stored in-memory. There are two key benefits:
1. This doesn't require any user to import pages into a `BTreeMap`, rather enabling them to store pages in a way which is natural to their I/O, caching, and so on.
2. Leads to cleaner code
> page-set: make generic

- core/src/page.rs
- core/src/page_id.rs
Inside `traverse_children`, I used `unwrap` for one main logical reason: the operation of traversing the tree operated by the Cursor must be infallible given the information of the KeyPath. A KeyPath is an arbitrary string of 256 bits, so there should be no way to pass a wrong KeyPath that could lead to a wrong construction of the child index pased to `child_page_id`. 
Despite that, I still think it's valuable to return an error on `child_page_id`, mostly to detect possible bugs introduced during development. 
What do you think? Do you think instead it should be handled and `traverse_children` should return a more general error like `TraverseError`, not only covering `MissingPage` but also `ChildPageIdError`?
> page_id: error handling in child_page_id

- Cargo.lock
- core/Cargo.toml
- core/src/page_id.rs
PageId is kept as `[u8; 32]` and the conversion to
`Uint<256, 4>` is only made where PageId needs to be
treated as a 256-bits integer
> page_id: use ruint to handle 256-bits integers

- core/src/page.rs
- core/src/page_id.rs
- nomt/src/page_cache.rs
- nomt/src/store.rs
Struct `PageId` now wraps `Uint<256,4>` to enable bounds checking at creation
and to allow for ordering of that struct.
This could simplifies future page caching mechanisms.
> page_id: move logic into struct PageId using Uint

- core/src/cursor.rs
- core/src/lib.rs
- core/src/page.rs
- core/src/page_id.rs
- core/src/proof.rs
Gets rid of a bunch of code that was unnecessary for the dummy (test) cursor implementation.
Should not be considered final, just roughly what I mapped out as needing for the update, plus the skeleton in #42
> refactor: cursor API in prep for blocking on I/O and multi-update

- core/src/page.rs
- core/src/page_id.rs
- nomt/src/cursor.rs
Probably less efficient than storing an iterator over chunks,
because now BitSlice needs to be constructed each time.
But useful to avoid propagating the requirements of dealing
with lifetimes in all structs that will store the iterator
> page_id: make PageIdsIterator own the KeyPath

- core/src/proof.rs
- core/src/update.rs
This implements the update verification algorithm, by which we can
ensure that a set of put/delete operations leads to a particular new root by doing the calculations
with only a series of path proofs.
> feat: update verification

- Cargo.lock
- nomt/Cargo.toml
- nomt/src/cursor.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
by leveraging rw-pass-cell for bulk locking for pages and
using a concurrent analog of HashMap.
This also localizes the dirty map in the cursor and makes
it local to the commit thread.
> avoid lock contention in page cache

- nomt/src/lib.rs
- nomt/src/store.rs
We read the root in `Nomt::open` but never wrote it, which lead us to assume an empty DB when opening an existing one.
> feat: write root in commit

- nomt/src/lib.rs
returns the newly computed root from `commit_and_prove`.
This is less racy and is more aligned with the API shape we 
had in mind originally.
> return new root from commit_and_prove

- core/src/proof.rs
- core/src/update.rs
1. hashing too much due to incorrect shared depth calculation
2. visiting wrong node depths when building sub-trees
> fix: update bugs

- nomt/src/lib.rs
otherwise, we'd pass incorrect info to `update::update`.
> fix: only visit leaves which have writes

- benchtop/src/main.rs
The previous iteration was not gathering enough entropy, which caused lots of collisions. The first
collision was at approximately N=28000, which isn't too far off from the expected 2^(32/2) = 65535
that we'd need in theory. The solution is to gather more bits of key material. We could probably
get away with gathering less, like 64 bits, while doing tests with millions of keys, but we can
optimize later. The XORshift should be very fast.
The current method gives 11,661 collisions in the first 10M accounts, or ~0.1% and 112 collisions in the first 1M accounts.
> benchtop: better key path gen

- .gitignore
- Cargo.lock
- nomt/Cargo.toml
- nomt/tests/add_remove.rs
- nomt/tests/common/mod.rs
This adds an integration test for root calculation consistency when building and subsequently 
deconstructing a trie.
Annoyingly, RocksDB doesn't seem to work with a temp dir on my machine. We will address that when
other tests are added.
> test: add an integration test for correctness

- benchtop/src/main.rs
Use the regular [`new`](https://docs.rs/hdrhistogram/latest/hdrhistogram/struct.Histogram.html#method.new) to create the histogram. Otherwise, it leads to value-out-of range errors during very slow operations.
> fix the histogram bounds

- benchtop/src/main.rs
when figures are large, print "us", "ms", or "s"
> chore: display prettier numbers in benchtop

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- nomt/Cargo.toml
- xtask/Cargo.toml
- xtask/src/bench.rs
- xtask/src/cli.rs
- xtask/src/main.rs
- xtask/src/nomt.rs
- xtask/src/sov_db.rs
- xtask/src/timer.rs
The following pr is very experimental. Every `unwrap`/`panic` and missing comments will be added/fixed in the following pull requests if this structure is accepted.
Things to notice are:
+ currently using `--initial size` with nomt makes it panic. Not sure if the error is due to how it is used or if there is a problem in nomt implementation.
+ using sov-db required a downgrade of `rocksdb` dependency. I will try to find another solution instead of downgrading it in nomt.
+ I'm not sure how keys should be handled... sov_db seems to re-hash keys to create separate databases where key, key_hash, and values are stored. I still need to figure out how they handle this; after that, I will be able to understand which approach is the best to use in benchmarking. For now, re-hashing of the keys is …
> bench: initial structure

- fuzz/fuzz_targets/api_surface.rs
the harness's "committed" overlay didn't allow deletions.
> chore: fix fuzz harness delete bug

- core/src/proof.rs
- core/src/update.rs
- nomt/src/lib.rs
- nomt/src/rw_pass_cell.rs
- nomt/tests/common/mod.rs
- xtask/src/main.rs
- xtask/src/nomt.rs
removing unused imports, allow unused for guard and fmt.
> chore: squash warnings

- core/src/update.rs
- nomt/src/lib.rs
- nomt/tests/add_remove.rs
This lead to pretty large logic errors when reading, not just writing keys.
The test diff fails on master and passes with this changeset.
> fix: only put write terminals when there are writes

- core/src/cursor.rs
- core/src/trie.rs
- core/src/update.rs
- nomt/src/cursor.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
- nomt/src/store.rs
This addresses almost all of the comments from #84, which were largely style nits with one larger issue.
#84 contained hacky behavior, where the user of the Cursor had to explicitly clear leaves while also
being careful not to overwrite leaves while building a tree upwards. These were major undocumented
footguns.
This fixes that, by using `NODES_PER_PAGE` bits at the end of each page to keep track of which
positions are leaf data and which are nodes. When a node is written beyond the end of the leaf,
the leaf is invalidated and our bit vector lets us subsequently overwrite the leaf without clearing
the previous node.
> refactor: fix review from 84

- Cargo.lock
- core/Cargo.toml
- core/src/update.rs
- nomt/src/cursor.rs
We were spending a lot of time while warming up and updating in the cursor doing bitvec ops when moving up and jumping around.
I think that this plus #97 could be interesting.
> opt: store node index in cursor

- Cargo.lock
- core/src/cursor.rs
- core/src/proof.rs
- nomt/src/cursor.rs
- nomt/src/lib.rs
We were redundantly recording paths for all encountered terminals. The `seek` function already
traversed to the node, so it's a simple matter to record all the siblings at that time.
In the future we could even record the page IDs and pages encountered during a `seek`. This would
be useful for two reasons:
1. providing pages directly to the `Cursor` used in `update`
2. parallel update scheduling
I also removed the `seek` function from the `Cursor` trait as it's not used in `update` since #96
> record path in seek

- xtask/src/timer.rs
remove histogram bounds and print prettier timings (modifications already made on benchtop in #102 #105)
> bench: timer updates

- xtask/src/cli.rs
- xtask/src/custom_workload.rs
- xtask/src/main.rs
- xtask/src/timer.rs
- xtask/src/workload.rs
from the cli, it is now possible to execute workloads like:
set_balace (heavy_write), heavy_read, heavy_update, or heavy_delete
> bench: add custom workload

- xtask/Cargo.lock
- xtask/src/bench.rs
- xtask/src/custom_workload.rs
- xtask/src/transfer_workload.rs
- xtask/src/workload.rs
Useful to avoid rebuilding all actions before applying them and
important to be able to prepare the backend and apply the actions separately.
> bench: separate workload init and run

- xtask/src/backend.rs
- xtask/src/bench.rs
- xtask/src/cli.rs
- xtask/src/main.rs
- xtask/src/nomt.rs
- xtask/src/sov_db.rs
- xtask/src/workload.rs
Init will initialize nomt backend given a workload and run will execute it skipping the
initialization phase. It allows the possibility of easily using samply over workloads,
example of usage:
```shell
cd xtask
cargo build
./target/debug/xtask init -n transfer -s 10000 -c 15
samply record target/debug/xtask run -n transfer -s 10000 -c 15
```
> bench: add cli init and run commands

- xtask/Cargo.lock
- xtask/Cargo.toml
- xtask/src/cli.rs
- xtask/src/custom_workload.rs
- xtask/src/workload.rs
Specified workloads can now be `randw`, `randr`, `seqw`, or `seqr`.
Sequential workloads will start from a random address.
> bench: change workloads to rand or seq rw

- benchtop/src/backend.rs
- benchtop/src/custom_workload.rs
- benchtop/src/nomt.rs
- benchtop/src/sov_db.rs
- benchtop/src/sp_trie.rs
- benchtop/src/timer.rs
Measure 3 things:
1. entirety of the workload
2. read latency
3. time consumed in commit and prove
example:
```shell
Running `target/release/benchtop bench -b nomt,sov-db,sp-trie -n transfer -s 10000 -i 1`
nomt
mean workload: 301 ms
mean read: 2136 ns
mean commit_and_prove: 201 ms
sov-db
mean workload: 2653 ms
mean read: 63102 ns
mean commit_and_prove: 1345 ms
sp-trie
mean workload: 229 ms
mean read: 2334 ns
mean commit_and_prove: 85032 us
```
> bench: add more granular timing

- nomt/src/lib.rs
I "fixed" the unused crate dependency warnings by removing the lint altogether. It doesn't play
nicely with crates that we bring in for integration tests.
https://crates.io/crates/cargo-udeps might be better.
> chore: fix lint warnings

- nomt/src/cursor.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
This extracts the seek function to a new `Seeker` whose only purpose is to seek (repeatedly)
This is in anticipation of a rewrite of `PageCursor` to store `Vec<Page>` directly, rather than
wrapping a `PageCache`.
> refactor: extract seek from pagecursor

- core/src/cursor.rs
- core/src/update.rs
- nomt/src/cursor.rs
- nomt/src/page_cache.rs
hint fresh pages in update
We are currently querying the disk store for pages which are provably fresh, causing unnecessary
I/O in the critical section.
This shows about a 15% reduction in `update` runtime as a result.
before: https://share.firefox.dev/49QW4sv
after: https://share.firefox.dev/3xPp3Q0
> feat: hint when writing into empty pages

- benchtop/src/bench.rs
- nomt/src/page_cache.rs
- nomt/src/store.rs
This reverts commit 55cd845204d3b813e2f78627a2bf2f67536f8b9f.
I over-eagerly merged it. It's not clear that this results in any optimization and complicates the code.
> Revert "opt: use iterator to seek for pages"

- nomt/src/page_cache.rs
We initially prefetch `PREFETCH_N` pages along the path to any given key. By the time the `seek`
operation is completed, we may know in advance that several of these page fetches were simply unnecessary.
By canceling these pre-fetches, we allow the page-fetch workers to avoid performing unnecessary I/O.
This effectively clears the workload of the page-fetch workers when the warm-up workers conclude,
leaving them free to work on the next transaction of pre-fetches.
> refactor: cancel unneeded page fetches at the end of seek

- .gitignore
- benchtop/src/backend.rs
- benchtop/src/bench.rs
- benchtop/src/nomt.rs
- benchtop/src/sov_db.rs
- benchtop/src/sp_trie.rs
- benchtop/src/workload.rs
#149 introduces a useful feature, but it comes with the side effect of causing all workloads to be executed on top of the previous one.
This pull request changes how workload initialization and execution processes run: initialization runs on a database, while the execution runs on a copy of the initialized database.
There is redundant code between the `open` and `open_copy` functions within each backend due to an issue with "`backend::Db` not being able to be turned into an object" when attempting to move `open` inside the trait.
Suggestions for avoiding the redundant code are welcome!
> bench: fix initialize backend only once

- nomt/src/rw_pass_cell.rs
This introduces a `RegionedWritePass` that can be split according to an implementation of the
`Region` trait. I don't really care about the abstraction here, but I followed the lead of
`RwPassCell` in being generic and made a generic implementation.
I have a very particular concrete use-case in mind for this: parallel trie update.
The idea is that we have N worker threads, and we give them each 1/N of the read/writes to process.
We can use the `RegionedWritePass` as not only protection for writes, but also as a way to easily
schedule the update. I'll elaborate.
We give each worker thread a pass corresponding to the sections of the trie they are responsible. The domain is a `min, max: PageId`. This pass has a parent which corresponds to the next point of contention with another worker …
> feat: introduce a RegionedWritePass which allows write-locking specific regions of data

- benchtop/src/bench.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/timer.rs
- benchtop/src/workload.rs
Add two subcommands to the `bench` command to enable the following functionalities:
1. Isolate benchmarking by executing each workload on a copy of the initialized backend
2. Sequential benchmarking by continuously repeating workloads on the same backend until a specified time or operation limit is reached
The possibility of manually interrupting the execution is out of scope for this PR because it would require some new dependencies (handling ctrl+c), therefore, it will be implemented separately in a follow up pr
> bench: workload execution type

- nomt/src/rw_pass_cell.rs
If both `drop` and `consume` decrease `parent.remaining_children` by one,
then after calling `consume`, the final result would be a decrease of two
in `parent.remaining_children`
I tried to avoid making `consume` mandatory, but I couldn't find a way to make
the usage of `parent.remaining_children` work in the correct order.
If inside `drop` the value is fetched and subtracted by 1 with `Ordering::AcqRel`,
and then inside `consume` it is just loaded with `Ordering::Acquire`,
there are scenarios where both `consume` calls on two `write_pass` would return the same
`parent.remaining_children`, and then none of them would yield the parent region.
> rw_pass_cell: remove WritePass custom Drop

- Cargo.lock
- nomt/Cargo.toml
- nomt/src/page_region.rs
- nomt/src/rw_pass_cell/loom_tests.rs
- nomt/src/rw_pass_cell/mod.rs
Loom provides some drop-in replacements to test concurrent programs.
`UnsafeCell` and `Arc` are not drop-in replacements.
The solution to this problem is:
- Do not substitute Arc because `loom::sync::Arc` does not provide the `downgrade` method, thus Arc usages will not be tracked by loom
- Add some conditional compilation to support the usage of `loom::cell::UnsafeCell` only during loom testing
To run loom tests, use the command: `RUSTFLAGS="--cfg loom" cargo test rw_pass_cell --release`
The solution is not the cleanest one. Any suggestions are welcome!
> rw_pass_cell: introduce loom testing

- .gitignore
- benchtop/Cargo.lock
- benchtop/Cargo.toml
- benchtop/src/bench.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/regression.rs
- benchtop/src/timer.rs
- benchtop/src/workload.rs
simple cli command that parses a toml file that contains a set of workloads with an expected
average duration, executes them in, and then compares the results
I have considered a more sophisticated and reliable method for managing regression testing, but for now, the simplest and valuable approach may be to maintain a manually updated reference 
I is very simple to use:
```shell
benchtop git:(gab_bench_workloads_exec_type) ✗  ➜ cargo run --release -- regression -i regression.toml
Compiling benchtop v0.1.0 (/home/gabriele/Documents/thrum/nomt/benchtop)
Finished release [optimized] target(s) in 8.66s      ld `op_limit` on 
Running `target/release/benchtop regression -i regr.toml`
Executing Workload: random_read_20
Sequential - Improvent 
Previous mean:  909 ms
Current mean:  224 ms
Current …
```
> bench: add regression tool

- benchtop/src/backend.rs
- benchtop/src/bench.rs
- benchtop/src/cli.rs
- benchtop/src/custom_workload.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- benchtop/src/regression.rs
- benchtop/src/sov_db.rs
- benchtop/src/sp_trie.rs
- benchtop/src/transfer_workload.rs
- benchtop/src/workload.rs
I reworked benchtop to produce a new workload each iteration rather than applying the same actions
each time.
This actually brings the sp-trie benchmark more in line with NOMT on commit, because it has a fast
path for when trie nodes aren't altered, and this is what we were seeing before.
I think this will lead to much more realistic testing.
I also removed a few things:
1. Sequential workload - because we hash keys, they're not sequential. I still would like to have
this at some point, but it doesn't make sense until we don't hash keys.
2. Action - because generating fresh actions each time is really what we should be doing.
> refactor: benchtop workloads unique each iteration; remove unused code

- core/src/trie_pos.rs
- core/src/update.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
We previously used a generalized `Cursor` for updates, but this had some weaknesses. In particular,
the general API meant there was less room for optimization.
In a prior refactor, we extracted `Seek` from the Cursor. This is essentially doing the same thing
for updates. I foresee being able to remove the `LEAF_META` from the pages as a result.
This also prepares for parallel update logic, by allowing the `PageWalker` to have an optional
`parent_page: Option<PageId>`. Rather than compacting updates all the way to the root, when this
parent page is provided, the walker just stores the nodes it _would have_ written to the parent.
If we have e.g. 8 workers, they can each work on a `PageWalker` with `parent_page = ROOT_PAGE_ID`
and then the last worker can apply those updates to the root …
> feat: introduce a PageWalker for updating without using a cursor

- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
This removes the leaf_meta bitfield from pages. It was only necessary because the cursor API
couldn't rely on a user removing the leaf children before writing nodes below the leaf. Now that
we've moved update over to the page-walker in #170, it is no longer necessary.
> refactor: remove leaf_meta

- Cargo.lock
- Cargo.toml
- examples/commit_batch/Cargo.toml
- examples/commit_batch/src/lib.rs
- examples/commit_batch/src/main.rs
- examples/read_value/Cargo.toml
- examples/read_value/src/main.rs
- examples/witness_verification/Cargo.toml
- examples/witness_verification/src/main.rs
Introducing the initial version of examples. They are:
1. read_value :: Simply open nomt and read a value from it
2. commit_batch :: Describing all the processes required to effectively read and write values to storage, explained through a simple example of a transfer workload
3. witness_verification :: Explaining how witnesses should be verified
> examples: init read_value, commit_batch and witness_verification

- benchtop/src/backend.rs
- benchtop/src/bench.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- benchtop/src/regression.rs
This introduced --fetch-concurrency / -f to configure nomt to use the specified number of threads. The default is 1.
> benchtop: plumb fetch concurrency from cli

- Cargo.lock
- nomt/Cargo.toml
- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
- nomt/src/seek.rs
This shards the page cache based on the number of workers, and gives each shard an LRU cache.
A further step would be to give each worker a mutable handle to their shard during `update`.
not implemented: cache eviction during retrieval.
> feat: sharded page cache + LRU

- benchtop/src/nomt.rs
- examples/commit_batch/src/lib.rs
- examples/read_value/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/lib.rs
- nomt/src/options.rs
- nomt/src/page_walker.rs
- nomt/tests/common/mod.rs
This helps not changing N places when adding an option and also also helps versioning somewhat.
> nomt: encapsulate options

- Cargo.lock
- benchtop/src/backend.rs
- benchtop/src/bench.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- nomt/src/lib.rs
- nomt/src/metrics.rs
- nomt/src/options.rs
- nomt/src/page_cache.rs
measure page_requests_count, page_cache_misses, page_fetch_time, and value_fetch_time
The decision I have made for now is to collect metrics based on nomt instance. Metrics are collected across all sessions and printed on-demand. If you prefer to collect them per session, it would be easy to update. Thinking about #195, it would probably be nice to remove the initialization from the metric collection. This can be addressed in a follow-up
example outcome:
```shell
Running `target/debug/benchtop bench sequential -b nomt -n randrw -s 25000 -c 15 --op-limit 100000`
metrics:
page requests         747026
page cache misses     174420 - 23.35% of page requests
page fetch mean       10232 ns
value fetch mean      8437 ns
nomt
mean workload: 2535 ms
mean read: 9712 ns
mean commit_and_prove: 1946 ms …
```
> add optional metrics collector

- benchtop/src/sov_db.rs
This reworks the sov-db bench to faithfully follow what sovereign-sdk does.
The previous approach was only writing to an in-memory map, though it was reading from an (empty)
rocksdb instance. We now commit this map to disk. This required reimplementing a "query manager"
trait, as the vanilla SnapshotManager does not allow us to manually commit to disk.
> benchtop: rework sov-db to commit to underlying DB

- benchtop/src/sov_db.rs
- benchtop/src/sp_trie.rs
1. read the root from the underlying DB
2. use prefixed memory DB to handle key prefixes
note: if we use ParityDB (and IMO we should; it's supposed to be better), we would have to sanitize the prefixes.
> chore: fix sp-trie in benchtop

- nomt/src/lib.rs
- nomt/src/metrics.rs
- nomt/src/page_cache.rs
This PR aims to address the following comment: https://github.com/thrumdev/nomt/pull/193#discussion_r1605440239
The main problem is handling interior mutability while working with Sync types. ~~This solution utilizes immutable structs so that metrics can be accessed from multiple threads and allows working with atomic types.~~
The names `Metrics` and `Metric` may not be the best choices, but I couldn't think of alternatives. Suggestions are welcome!
> refactor: metrics are referenced with enums

- nomt/src/lib.rs
Currently, the `committer` sends "signals" to the `CommitPool`. It starts using a round-robin approach to send `warm_up` signals. Once it is time to `commit_and_prove`, the `committer` sends a `Prepare`, followed by a `Commit`, to all `CommitPool`'s threads.
The comments that I removed were, if I'm not mistaken, still referring to the old implementations where there was only a commit thread that needed to wait on all `fetch_tp`'s threads to finish fetching all pages. Now there could be commit threads that start committing while others are still waiting to finish a `warm_up` signal.
All of this is to explain why I think this comment should be removed and to double-check my understanding of the new commit mechanism
> commit_and_prove docs: remove old comment

- Cargo.lock
- bitbox/src/beatree/allocator/free_list.rs
- bitbox/src/beatree/allocator/mod.rs
- bitbox/src/beatree/bbn.rs
- bitbox/src/beatree/leaf/node.rs
- bitbox/src/beatree/leaf/store.rs
- bitbox/src/beatree/meta.rs
- bitbox/src/beatree/writeout.rs
- bitbox/src/io.rs
- bitbox/src/sim/mod.rs
- bitbox/src/sim/read.rs
- bitbox/src/store.rs
- nomt/Cargo.toml
- nomt/src/lib.rs
Basically, we add the module io.rs to NOMT without actually moving it in-tree. The reasoning for this is that we are not yet ready to move this file, but there is still some work pending by R on the btree side.
This comes with some adjustments, like moving Page and PAGE_SIZE under io.rs rather than store.rs
> Link io to nomt

- bitbox/src/beatree/ops/update/branch.rs
previously this wasn't actually skipping the item to delete
> bug: handle possibly_deleted items in branch correctly

- nomt/src/lib.rs
solve dependency and imports problems and update wal entry to support 32 byte PageId
> bitbox: init adjustments

- nomt/src/bitbox/beatree/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/io.rs
- nomt/src/lib.rs
The main point of this PR is that we shouldn't have two copies of the io module, one in NOMT and one in bitbox. I chose to use the main NOMT location, but maybe having it in bitbox makes more sense. Something for a follow-up.
> chore: move io module to NOMT main

- nomt/src/bitbox/beatree/allocator/mod.rs
- nomt/src/bitbox/beatree/mod.rs
I am not sure about the fix here, but it seems to work. The `unwrap` in `commit` was wrong, and now it returns the marker value of `0`. I also added a constant as a slight code quality improvement.
> fix: support empty free-list properly in allocator commit

- nomt/src/bitbox/beatree/writeout.rs
Dropping a `File` _closes_ the FD. This PR converts the `File` back into an FD so we don't close files halfway through writeout when we need to extend the length.
> fix: don't drop FDs halfway through writeout

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/reconstruction.rs
- nomt/src/beatree/ops/update/branch.rs
- nomt/src/beatree/ops/update/leaf.rs
- nomt/src/beatree/ops/update/mod.rs
LSB0 was causing incorrect lexicographical comparisons, since it reversed the order of bits in the byte. This switches everything to MSB0.
> fix: use MSB0 bit-order for separators and key comparisons

- nomt/src/beatree/ops/update/branch.rs
- nomt/src/beatree/ops/update/leaf.rs
after a successful split, we previously weren't resetting the ops / separator override / gauge. this led to all ops carrying over to the next leaf / branch.
> fix: reset after splitting

- nomt/src/beatree/branch/mod.rs
- nomt/src/beatree/branch/node.rs
Since `()` is a ZST, `checkout` was broken as `(*mut ()).offset(X)` is a no-op. All the branches being handled out pointed to the beginning of the mapped region. Changing the type to `*mut u8` fixes that.
> fix: use *mut u8 in BNP instead of *mut ()

- nomt/src/beatree/branch/node.rs
this was being measured incorrectly, causing us to request 8x the branch size from the slice.
> fix: branch varbits should index with body size in bytes, not bits

- nomt/src/beatree/ops/update/leaf.rs
this off-by-one caused leaves to store items which fell before their separator, leading to havoc.
> fix: off-by-one in leaf bulk loading

- nomt/src/beatree/writeout.rs
- nomt/src/store.rs
This is not the final stage for the writeout module; it functions in tests, but this pull request should be followed by either #270 or a variation of the `MetaSwap` struct
> beatree: change writeout workflow

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/bitbox/mod.rs
also reduce the default DB size. we don't need 8GB every test run.
> fix: handle empty free-list case correctly in preallocate

- benchtop/src/backend.rs
- benchtop/src/bench.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- examples/commit_batch/src/lib.rs
- examples/read_value/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/reconstruction.rs
- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
- nomt/src/options.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
- nomt/src/seek.rs
- nomt/tests/common/mod.rs
This comes with an extremely shitty but correct rewrite of `seek`, which I intend to replace with a fast io_uring bitbox prober in a follow-up.
> refactor: decouple page cache and store

- nomt/src/bitbox/store.rs
alternative to #281 
We originally allocated an extra page in bitbox as a meta page. Now that metadata is handled elsewhere, we no longer need this extra page.
> fix: remove +1s in bitbox page offset calculations

- nomt/Cargo.toml
- nomt/src/bitbox/wal/mod.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
on UNIX-based OSs that are not linux, support I/O by spawning a bunch of worker threads that use synchronous syscalls
> feat: support all UNIX OSs with sync I/O worker threads

- nomt/src/bitbox/wal/mod.rs
This is a dirty hack, but highlights an issue with macOS support that we need to address sooner rather than later.
Although the WAL will grow indefinitely on macOS, with this change I am happy to report that our integration test now works on my Mac!
> hack: disable WAL pruning on non-linux platforms

- nomt/src/bitbox/mod.rs
in bitbox we were calling fsync twice in a row with no changes in-between because of the (now removed) meta page.
> chore: remove unnecessary double ht fsync

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/bbn.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/store.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
- nomt/src/store/mod.rs
- nomt/src/store/writeout.rs
As part of this refactor, we also no longer have to specify the number of handles we wish to create ahead-of-time. This is maybe a slight pessimization, since it means that we send a clone of the completion receiver to the io worker threads with every command. That's an extra atomic add/sub pair. On the off chance this is actually relevant to workload performance, I am pretty confident we can apply another approach to creating handles without breaking this abstraction.
> refactor: create an IoHandle wrapper around sender/receiver

- nomt/src/beatree/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
say goodbye to having separate I/O pools for each component!
> refactor: use a single, global I/O pool for writeout, bitbox, beatree

- nomt/src/bitbox/mod.rs
Previously, we were building a `Vec<(BucketIndex, Page)>`. This allocated over a page of memory for each item. Then, when we iterated over it, we were boxing each page, allocating a second page of memory for each item, essentially doubling the resident memory usage during bitbox sync. This caused OOM with commits that should have taken "only" 50% of the system memory.
That said, this still isn't the "end-state". There are still a lot of unnecessary copies that are going to slow us down. View this as a quick fix for the moment.
> fix: pre-box pages in bitbox sync

- nomt/src/page_cache.rs
This is currently a part of the diff of #308 and #306. Separating out for clarity.
Calling `record` with a metric that's not a timer causes a runtime panic when pages are not cached.
> fix: panic from calling 'record' on page cache misses

- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
If a read or write operation is not fully completed, the command is reapplied
Errors should now be properly handled. However, this has revealed a problem with the fsync command. Each fsync call performed through io_uring is failing with an "Invalid Argument" error message.
A fix will be included in a follow-up pr
closes #288
> io: retry read/write until complete

- nomt/src/bitbox/mod.rs
- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
- nomt/src/store/mod.rs
- nomt/src/store/writeout.rs
From https://kernel.dk/io_uring.pdf, in the section 'POLLED IO,' we can read: "Only op-codes that make sense for polled completion may be used on an io_uring instance registered with IORING_SETUP_IOPOLL" and fsync is not a valid opcode due to it being a blocking syscall.
This solves the problem of performing each fsync with the standard syscall without passing through io_uring.
This PR also fixes how the meta file was opened (without `O_DIRECT`) and corrects the usage of the metric PageCacheMisses.
> io: separate fsync from io_uring

- Cargo.lock
- nomt/Cargo.toml
- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
this lays the groundwork for exposing a thin wrapper for io_uring to NOMT commit workers.
it's not totally clear where this logic should live in the end. I'd like to encapsulate all probing logic in `bitbox` but managing the ht file descriptor is a little rough currently.
> feat: implement a basic page loader for bitbox pages

- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
- nomt/src/store/page_loader.rs
I've created a `store::PageLoader` which wraps a `bitbox::PageLoader` and exposes the same API.
The reason I opted for this approach is that there are a couple competing concerns:
1. To maintain ownership and liveness of the `ht_fd` within the `nomt::Store`.
2. To encapsulate probing logic, buckets, etc. within `nomt::bitbox`.
This lead to a little more code than necessary, but the boundaries are clean and this feels pretty maintainable to me. I'm open to suggestions on how else to structure this, though.
> feat: expose page loader from store

- core/src/update.rs
- nomt/src/commit/worker.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
This alters the `PageWalker`'s compact stage to bubble up an error when sibling leaf children are unavailable. Higher level code now reacts to this and fetches the page.
After this PR, we never request more pages than we need.
It's worth noting that we can only fetch a single page at a time this way, but the code is designed so there are many other page fetches ongoing at the same time. This ensures that I/O utilization is high unless this is one of the very last page fetches, in which case the lost potential I/O utilization of getting all the needed sibling pages at once is likely a rounding error.
> feat: fetch needed sibling leaf-children pages on demand

- benchtop/Cargo.lock
- benchtop/src/nomt.rs
- examples/commit_batch/src/lib.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/beatree/allocator/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
- nomt/src/seek.rs
- nomt/tests/common/mod.rs
I cleaned up warnings related to the refactors and changes in this stack.
The only change worth pointing out is that `tentative_write_slot` no longer requires `is_delete` as a parameter. This was always an extremely imperfect heuristic that led us to fetch _all_ the sibling leaf child pages, regardless of whether they were needed. Since we no longer eagerly fetch such pages, but instead do it reactively, this parameter is no longer needed.
> chore: clean up various warnings and TODOs after this stack

- nomt/src/page_walker.rs
this caused us to re-create pages that already existed, causing unbounded growth in bitbox
> fix: avoid creating fresh pages when overwriting leaf with leaf

- nomt/src/store/writeout.rs
avoid creating a file from the raw file descriptor, instead, use `libc::fsync` directly
https://github.com/thrumdev/nomt/pull/308#discussion_r1727186977
> chore: use libc::fsync in writeout

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/page_cache.rs
As per
[this][https://github.com/thrumdev/nomt/pull/323#discussion_r1730422403]
comment, allocation in `get_changed` is not insignificant. This commit
avoids allocation of a vector by passing an iterator.
> opt: do not materialize `changed` vec

- nomt/src/bitbox/wal/mod.rs
- nomt/src/store/mod.rs
1. Change the WAL entry tags from 0 and 1 to 1 and 2. This is needed for
distinguishing between actually written WAL entries and zeroed space.
2. Introduce `finalize` method that zeroes the WAL blob from the current
write position to the end of the page. Without this WAL might
possibly contain the leftover data from the previous syncs.
3. Fix the OOB condition from `cur > mmap_size` to `cur >= mmap_size`.
> fix: wal blob builder changes

- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/ops/update/mod.rs
The beatree update algorithm now only needs to load leaves when a merge occurs.
This is a significant speedup, because it was previously running with QD1 and fetching each leaf page as needed.
> opt: preload needed beatree leaves before update

- nomt/src/bitbox/wal/mod.rs
- nomt/src/store/writeout.rs
1. Fixes the size of backing mmap. It was passing pages but accepting
bytes.
2. Decreases `ht_remaining` after waiting for a completion in
`send_writes`.
> fix: WAL and HT

- nomt/src/beatree/leaf/node.rs
- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/leaf.rs
- nomt/src/beatree/ops/update/mod.rs
This handles the encoding of overflow cells and writing them in leaves.
In a leaf node, we use a 16-bit integer to encode the offset of each cell start. We take the high bit of this integer to encode whether the cell is an overflow cell or not.
When ingesting a value, if it's too large, we chunk it. Additionally, `LeafUpdater::ingest` has gained a callback for handling deletion of overflow cells. This will be fleshed out in the next PRs, along with loading of overflow values.
I am not focusing on optimization at all at the moment, as it's clear that the beatree update logic needs to be rewritten for parallelism in any case and any optimization at this stage would be wasted effort.
> feat: overflow cells, writing overflow values

- nomt/src/bitbox/mod.rs
- nomt/src/page_cache.rs
- nomt/src/seek.rs
- nomt/src/store/mod.rs
By switching page loads from `Vec<u8>` to aligned pages, I've eliminated all but one copy during page cache commit and hash table writes. This last copy can be elided by having writeout draw directly from the page cache, but that's a large piece of work that will require some discussion before diving into.
> opt: use aligned page in page cache and avoid some copies

- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/mod.rs
I added functions for reading and deleting overflow pages.
These are extremely inefficient, as we simply read one page at a time, but they do the trick.
Parallelizing I/O should come with a larger rewrite of this subsystem.
> feat: read and delete overflow

- nomt/src/bitbox/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/io/mod.rs
- nomt/src/seek.rs
- nomt/src/store/page_loader.rs
I had noticed that, due to the way `Seek` was written, warmup workers tended to use a full core.
This breaks up `Seeker::advance` into its constituent parts and has warm-up workers use a `Select` to avoid wasting CPU. I observed this using a lot less CPU now (20% in benchtop vs 100%)
Note that we do pay a cost here, though the effect wasn't measurably worse from what I saw. The cost is that sending warm-ups to the worker now has to wake up the thread, adding some overhead to reads and writes.
> opt: use Select to avoid busy-looping in warm up

- nomt/src/bitbox/mod.rs
- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
- nomt/src/store/writeout.rs
Closes #327. 
A seed is added to the meta page and used to salt the hash function for the hash-table. We draw this from high quality OS randomness.
> feat: add a random seed for the hash table

- core/src/multi_proof.rs
- core/src/multi_proof_verification.rs
- core/src/proof.rs
- core/src/update.rs
- nomt/Cargo.toml
Fix typo `features` to `feature` in `cfg` predicates. Also whitelist the
`cfg(loom)`.
See also:
https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html
https://doc.rust-lang.org/nightly/rustc/check-cfg.html
> chore: fix check-cfg warnings

- nomt/src/options.rs
- nomt/src/store/mod.rs
- nomt/src/store/writeout.rs
introduce an option to panic in the middle of a sync: after updating the
manifest but before writing out the bucket and meta pages.
> feat: panic on sync.

- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
This doesn't currently show up in profiles in overall performance, since so much time is wasted in the seeker, but anecdotally this caused PageWalker::advance_and_replace to now 21% of its time hashing, instead of the previous 7.5%.
> opt: avoid hashmap in page walker page diffs

- Cargo.lock
- nomt/Cargo.toml
- nomt/benches/beatree.rs
- nomt/src/beatree/benches.rs
- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/leaf.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/lib.rs
~~I couldn't find a better way to expose the private functions that need to be benchmarked besides starting to use this feature flag, which requires launching benchmarks with the following command: `cargo bench --features benchmarks`. Another problem is that I had to define the functions as `pub`~~
~~Do you have any other suggestions for handling this?~~
Update: To expose the benchmarks, there are currently three parts: the benchmarks implemented for the private function inside the same file, then a module `benches` inside the `beatree` module, and finally the `/benches/beatree.rs`, which simply calls the benchmark exposed by `beatree::benches`. This erases almost completely the code pollution of conditional compilation but requires a lot of modules to be defined as `pub(crate)` and the …
> beatree separate bench

- nomt/src/commit/worker.rs
- nomt/src/seek.rs
Rather than "re-seeking" key-paths which were already warmed up, we now account for these.
This brought commit times down by about 30% in the case that all key paths were warmed up already.
> opt: have commit draw from warm-ups instead of seeking again

- core/src/multi_proof.rs
- core/src/proof.rs
- core/src/trie_pos.rs
- examples/witness_verification/src/main.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
- nomt/tests/witness_check.rs
also updates triepos to use a u16
> opt: use TriePosition in witness rather than bitvec

- nomt/src/commit/worker.rs
- nomt/src/options.rs
- nomt/src/page_walker.rs
- nomt/src/store/writeout.rs
The code here had some issues with busy-looping on `try_send` and `try_recv`.
This actually caused livelocks, since we were calling `try_recv_*` when we failed to submit a write. The sequence of events would be this:
1. There would be no writes for e.g. the LN pending in the system but the I/O queue would be full.
2. We'd fail to submit the next LN write.
3. We'd then busy-loop on the next LN completion, which would never come because of (1).
It doesn't seem necessary to do this as a state machine per se. I might imagine that the inboxes could get pretty full, but we don't actually use the results and could easily just track the number of received items.
> fix: simplify writeout to block on send / recv

- nomt/src/store/mod.rs
This adds `F_NOCACHE` to all the FDs on mac.
It's not clear whether this is a good idea as it doesn't seem to actually be more performant. But it'll give us more consistency with any app-level caching we implement cross-platform.
> feat: avoid OS page cache on macOS

- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/bbn.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
this better reflects that it operates over an already opened file. `create` comes across as if this function participates in the creation of the database where in fact it actually doesn't.
> refactor: better naming for allocator open fn

- nomt/src/store/writeout.rs
otherwise there is a race between writing and fsyncing.
> fix: sync after recv completion

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/bbn.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
- nomt/src/bitbox/ht_file.rs
- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/io/mod.rs
- nomt/src/store/meta.rs
This changeset replaces ad-hoc reading files with a single function in
the io module called `read_page`.
The reasoning behind this change is to minimize the number of places
where we create a page. This should make it easier to introduce a common
page creation mechanism later on.
> refactor: introduce io::read_page

- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
- nomt/src/store/mod.rs
- nomt/src/store/writeout.rs
this is just for consistency. BBN right now doesn't merge pages[^1] and
I cannot see a good reason for doing this extra work. On the other hand,
for the future page pool implementation it *might* be better to
separate those in case those had different lifetimes.
[^1]: although technically BBNs are not `Page`, but the argument still
holds.
> refactor: don't merge ln pages for writeout

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/bbn.rs
- nomt/src/beatree/leaf/node.rs
- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/leaf.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/bitbox/ht_file.rs
- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/page_pool.rs
- nomt/src/io/unix.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
- nomt/src/page_diff.rs
- nomt/src/page_walker.rs
- nomt/src/seek.rs
- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
- nomt/src/store/writeout.rs
This changeset introduces a notion of page pool which changes the
approach we use to allocate the pages for IO. Instead of allocating
pages from the global allocator one-by-one, the page pool allocates a
big region of virtual memory from the system and slices it on pages
maintaining a freelist for efficient allocation.
This changeset is only a stepping stone and there is a bit of work to
do. Specifically, it introduces a concept of [`FatPage`] which is
relatively convenient to work with but at the cost of leaving some
performance on the table. Also, page pool's implementation is not the
most efficient out there. This is to be solved in future commits.
Suggestion for the review:
Most of the changes is plumbing: weaving the page pool into all the places page allocation happens.
> refactor: page pool

- core/src/proof.rs
- core/src/update.rs
- nomt/src/page_walker.rs
- nomt/tests/common/mod.rs
This loosens the assumptions of merklized page data.
We previously had a tacit assumption that all merkle pages were zeroed, so we had no need to explicitly write terminators.
Ongoing page pool refactors change that assumption and save us the cost of explicitly zeroing pages on alloc or release.
Now, when we create an internal node we explicitly zero the sibling if it's a terminator. This required some refactoring to pass the internal node data to the page walker.
> refactor: have page walker explicitly zero new internal terminator children

- nomt/src/io/page_pool.rs
This optimization changes the data structure by leveraging the fact that the regions are immutable once they were created. This allows us to avoid expensive locking after each access. The title is a bit of click-bait since locking still happens for freelist updates.
> opt: lockless page pool

- nomt/src/beatree/branch/mod.rs
- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/branch.rs
stop using a common prefix_len and instead use a vector of cells
to store different prefix_len values, one for each separator
> feat: new branch node encoding

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/branch.rs
- nomt/src/beatree/ops/update/mod.rs
This pr enables the construction of a BranchNode, allowing the specification of a set of separators that share the prefix while all others do not share it and are completely encoded within the separators bitvector
> feat: branch encoding add prefix_compressed

- nomt/src/beatree/index.rs
- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/branch.rs
- nomt/src/beatree/ops/update/leaf.rs
- nomt/src/beatree/ops/update/mod.rs
This separates beatree branch and leaf update into stages.
The intention of this PR is to set the groundwork for parallelism, where worker threads will work on some of the leaves and some of the branches, and that we would divide up work differently for each stage.
This also simplified the dependencies of leaf and branch updaters, making them likely more testable.
> refactor: separate beatree update into leaf and branch stages

- nomt/src/beatree/benches.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/branch_updater.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
- nomt/src/beatree/ops/update/mod.rs
1. extract update stages to their own modules.
2. rename branch and leaf updater modules to branch_updater and leaf_updater
3. nit: stop exporting branch_updater and leaf_updater publicly
> refactor: reorganize beatree update modules

- benchtop/src/timer.rs
- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/store/mod.rs
This adds some parallelism to the leaf stage of beatree update.
The core idea is to give each worker a half-open range of `[low_separator, high_separator)` to work on. The worker logically is responsible for making all updates to those nodes. The worker does a left-to-right sweep with splits and merges.
If a worker needs to perform a merge that uses the node beyond the end of its range, it sends a message to the worker to the right. The worker on the right will answer that message with information about the nodes it's updated to extend the range of the worker on the left.
We set up the half-open ranges so that they start right at the first item of the worker and end right before the first item of the next worker. This means that workers already have a lot of buffer to perform merges and …
> feat: parallel beatree leaf updater

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/update/branch_updater.rs
This uses Gabriele's previous work on limiting the number of prefix-compressed items in the branch.
This adapts the gauge and handles the degenerate cases where a node jumps from underfull to overfull with the addition of a single new item that collapses the shared prefix.
The test shows an extreme example of the type of issue that this is countering.
> feat: stop branch prefix compression in extreme cases

- nomt/src/bitbox/mod.rs
- nomt/src/io/page_pool.rs
This leverages the opportunity enabled by [#397] and deferred
by [#400].
[#397]: https://github.com/thrumdev/nomt/pull/397
[#400]: https://github.com/thrumdev/nomt/pull/400
> opt: remove unconditional zeroing of a page

- nomt/src/beatree/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
For now, this just initiates the syncing logic from tasks submitted on a
thread pool, meaning that syncing of beatree and bitbox happens in
parallel.
This yields around 10% improvement in running time of sync.
> opt: run beatree and bitbox prepare sync in parallel

- nomt/src/beatree/ops/update/leaf_stage.rs
The cutoff needs to be removed only if all right neighbors have deleted all their leaves, and thus the current worker needs to create the new last leaf, which is done by removing the cutoff of the base leaf.
If the new_entry received from the request_range_extension is going to be the new base, it never requires removal of the cutoff. If the received entry is the last one, then new_entry.next_separator will already be None
> fix: avoid removing cutoff from base leaf

- nomt/src/beatree/ops/update/leaf_stage.rs
The branch_stage requires a sorted vector of changes. Thus, the leaf_stage needs to sort them when receiving the output of all workers
> fix: leaf_stage sort worker changes

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/bit_ops.rs
- nomt/src/beatree/ops/update/mod.rs
After profiling #412 and #413, I have noticed a noticeable decrease in performance related to the struct introduced to wrap the branch node prefix and separator.
However, the more performant `reconstruct_key` function needed some raw data to work on. Thus, in contrast to previous PRs, this one introduces as little changes as possible to allow `reconstruct_key` to access raw bytes directly.
> opt: reconstruct_key works on raw bytes

- core/src/page_id.rs
- nomt/src/page_cache.rs
the Arc clone was 5% of merkle update time.
the default clone implementation for PageId involved into_iter().collect(), when it should've been a memcpy
> opt: avoid cloning Page in locate_child and make PageId::clone cheaper

- nomt/src/seek.rs
`take_completion` needs to prioritize single-page-requests and thus before taking completed requests it waits for the single-page-request before continuing with other requests
> fix: prioritize completing single-page-request

- nomt/src/bitbox/writeout.rs
- nomt/src/store/sync.rs
After the recent parallel refactor, we weren't truncating the WAL after successfully writing.
This caused start-up after init to take a very long time.
I added that back, but also am curious if we have a better way of detecting whether WAL changes are outdated.
> fix: truncate WAL after writing HT file

- nomt/src/lib.rs
- nomt/src/seglog/mod.rs
- nomt/src/seglog/segment_filename.rs
- nomt/src/seglog/segment_rw.rs
This commit introduces a segmented log (seglog for short). It is an
append-only log that allows pruning old items.
The seglog module provides a storage abstraction that supports appending
data sequentially. It is designed to handle large volumes of data
efficiently by segmenting the log into manageable parts. Key features
include:
- **Append-Only**: Data can only be appended, ensuring a consistent and
ordered log.
- **Pruning**: Old data can be pruned from the beginning of the log to
reclaim space, keeping the log size manageable.
- **Segment Management**: The log is divided into segments, each with a
maximum size limit. New segments are created as needed, and old
segments can be removed once they are no longer needed.
- **Record Management**: Each record has a unique ID, and the module …
> feat: introduce seglog

- benchtop/src/nomt.rs
- nomt/src/lib.rs
- nomt/src/store/mod.rs
- nomt/tests/common/mod.rs
- nomt/tests/extend_range_protocol.rs
We previously wanted to avoid cloning these values while updating RocksDB. This is no longer necessary, and it incurs no performance overhead to take these `Vec`s by-value, since we don't clone them at all. In fact, this PR removes a deep clone.
The impetus for this change is to alter NOMT's API to support threaded access to `Session`s.
> refactor: make NOMT values raw `Vec`s, not Rc

- benchtop/src/main.rs
- benchtop/src/nomt.rs
- benchtop/src/timer.rs
Example output from benchtop following this PR:
```
nomt
mean workload: 378 ms
mean read: 92178 ns
mean commit_and_prove: 222 ms
throughput: 26388.9 ops/s
```
> feat(benchtop): print mean throughput

- benchtop/src/nomt.rs
- examples/commit_batch/src/lib.rs
- examples/read_value/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/beatree/mod.rs
- nomt/src/commit/mod.rs
- nomt/src/lib.rs
- nomt/src/seglog/mod.rs
- nomt/tests/common/mod.rs
This PR removes the `tentative_read_slot` and `tentative_write_slot` APIs from `Session` and replaces them with `read(key) -> value` and `warm_up(key)` APIs.
There are motivations for this change:
1. Supporting warm-ups with app-level caching. If the user has an app-level value cache, they need some way to tell NOMT to warm up the path. This requires a `warm_up` function to exist.
2. Avoiding redundant warm-ups with read-then-write patterns. In the current state of the API, we call `warm_up` twice for a key: once when we read it, and once when we write it.
- This inefficiency might not be avoidable in general computation, but at least this way the user has the ability to elide redundant calls as far as their execution environment permits.
3. Avoiding warm-ups for reads when not …
> feat: remove tentative_*_slot APIs, replace with read and warm-up

- nomt/tests/fill_and_empty.rs
Decreasing `db_size` to make tests faster without losing the efficacy of the tests. Still, around 3k leaves are created in total for each fill and empty test. The one using 64 workers is averaging 200 range extension requests
> chore: update fill_and_empty tests

- nomt/src/beatree/ops/bit_ops.rs
I was running into an issue where the separator was being shifted left by 5 bits but then only getting 3 bits from the next byte.
e.g. `11111111` was becoming `11100000` and then `11100111`, which was wrong. The initial fix just changed an `amount` to `(8 - amount)`.
But the `mask` didn't seem useful in this case (it was being generated as `11101111`) so I removed it. What was it for? Is it still necessary?
> fix: left-shift bug in reconstruct_key

- nomt/src/seglog/mod.rs
- nomt/src/seglog/segment_rw.rs
I've noticed some warnings coming out from the seglog even when the code is used by the rollback.
So here I fix those and add `allow(dead_code)` to seglog for now. This is already removed in the upcoming rollback PR.
> chore: clean up seglog

- nomt/src/beatree/ops/bit_ops.rs
Noticed this on master after `gt sync`.
> chore: clean up unused imports

- core/src/page_id.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/page_cache.rs
`shard_index_for` was super slow. This replaces it with a simple approach based on how we allocate the shards in the first place.
> opt: optimize shard_index_for

- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
- nomt/src/seek.rs
This is a refactor, and to some extent an optimization.
A single warm up thread is able to saturate all 3 I/O thread CPUs in my empirical tests.
It solves some problems, as well:
1. Makes it easy to give each commit worker a list of everything that's been warmed up, which was a prior issue in the code (workers only had a list of what they had warmed up)
2. potential for more simplification / modularization
3. potential for less granular cache shard locking
4. With many warm-up threads, threads were likely to be idle and blocking on `warmup_rx.recv()`. This meant that the sender (critical path workload threads) were paying a cost for waking up the receiver. In a cursory sample, this problem seems to have gone away.
> refactor: use only a single warm-up thread

- core/src/multi_proof_verification.rs
- core/src/page_id.rs
- core/src/trie_pos.rs
- core/src/update.rs
- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/ops/update/branch_updater.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/page_region.rs
- nomt/src/page_walker.rs
- nomt/src/seglog/segment_rw.rs
avoid using glob imports for tests. Only one exception: prelude.
> chore: de-glob imports

- nomt/src/rw_pass_cell/mod.rs
this removes nonexistent references.
> chore: fix rw-pass doc warnings

- Cargo.lock
- benchtop/src/nomt.rs
- nomt/Cargo.toml
- nomt/src/lib.rs
- nomt/src/options.rs
- nomt/src/rollback/delta.rs
- nomt/src/rollback/mod.rs
- nomt/src/rollback/tests.rs
- nomt/src/seglog/mod.rs
- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
- nomt/tests/rollback.rs
This changeset implements a rollback feature.
The rollback feature allows NOMT to roll back to
a previous commit state.
It is implemented by storing a reverse delta for
each commit. When rolling back, we apply the reverse
delta to the current state to restore the previous
state.
To gather the reverse delta NOMT collects the
prior values of the keys that are being modified
or removed. When committing, it uses this information
to create a reverse delta. To that end,
the Session object has a `preserve_prior_value` method
that the caller should call for each key that they wish
to preserve.
The definitive set of values to be committed is
determined by the `Nomt::commit` call. As such,
there is no issue with invoking this function for
values that may not ultimately be written.
Similarly, values …
> feat: rollback

- .github/workflows/ci.yml
this gets more important with #482 since it adds more jobs and that gets the total number of jobs to 4 when we only need 2 per PR.
> chore: run CI only on pull requests and pushes to master

- nomt/src/beatree/writeout.rs
- nomt/src/bitbox/writeout.rs
This optimization is a bit more tentative.
The overhead of sorting is relatively low, but it seems to help with the throughput of HT writes in particular.
> opt: pre-sort writes

- nomt/src/lib.rs
- nomt/src/rollback/mod.rs
- nomt/src/rollback/tests.rs
- nomt/tests/rollback.rs
This changeset implements an optimization suggested by @rphmeier to
elide fetches to the store for the keys that were passed in Nomt::commit
as ReadThenWrite.
Note that this doesn't check if that was the actual value and blindly
trusts the user to correctly specify the value, as doing so will
actually makes no sense performance-wise.
> opt(rollback): don't fetch read-then-write

- nomt/src/beatree/ops/update/leaf_updater.rs
Another solution could be to find another `LEAF_BULK_SPLIT_THRESHOLD` but I couldn't find any value which was passing the tests introduced in #493, thus a recursive call to split was the easiest solution to cover this edge case
> fix: stop split from creating too big right leaf

- nomt/src/commit/mod.rs
- nomt/src/lib.rs
- nomt/src/options.rs
It doesn't seem to be a given that warm-ups improve performance. In fact, in all the tests I ran, warm-ups were a pessimization. I believe this is due to the added SSD queue depth due to warm-ups impacting state read latencies - merkle commit was getting faster, but the workload was getting slower by an even larger amount. Therefore, I've made running warm-ups configurable, and disabled it by default.
> feat: make merkle warm-ups configurable, off by default

- nomt/src/options.rs
- nomt/src/rollback/mod.rs
- nomt/src/rollback/tests.rs
- nomt/src/store/mod.rs
We discussed potentially changing the way we dispatch the loads to async IO which would obsolete this setting, but I decided to submit this anyway in case for the time being.
> feat: configurable rollback tp size

- Cargo.lock
- benchtop/Cargo.lock
- nomt/Cargo.toml
- nomt/src/store/flock.rs
- nomt/src/store/mod.rs
- nomt/tests/exclusive_dir.rs
- nomt/tests/rollback.rs
Closes #483
This commit aim is to return an error message if another process tries
to use the same db directory, which is unsupported according to our
assumptions.
Note that this uses only advisory locking. It's still possible to mess
with the directory and containing files. It's the responsibility of the
user to prevent that and failure to do so can and will lead to
unexpected behavior.
A couple of words on my research of the problem and the taken approach.
There are mandatory and advisory locking. Mandatory locking is a feature of OS that reserves an exclusive right for a specific program to access a particular file. On Linux, mandatory locking is turned off by default and to be avoided (see [this](https://www.kernel.org/doc/Documentation/filesystems/mandatory-locking.txt)). macOS …
> feat: flock db dir

- nomt/src/beatree/ops/update/extend_range_protocol.rs
Starting the iteration with `separator` set to `None` caused the extension protocol to respond without providing the correct unchanged range if an inserted leaf was followed by an unchanged range
> fix: correctly detect unchanged ranges

- examples/commit_batch/src/lib.rs
- examples/read_value/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/lib.rs
- nomt/tests/common/mod.rs
- nomt/tests/exclusive_dir.rs
- nomt/tests/rollback.rs
I opted for a generic, but this could be refactored to a trait object if the API proves too clunky.
> feat: make NOMT generic over hash function

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/allocator/mod.rs
Some preliminary refactoring to prepare for pipelined beatree sync: where we write new pages while still computing changes to the btree.
At the end of this stack, I plan to remove the existing `AllocatorReader`/`AllocatorWriter` and hopefully the `leaf::store` and `bbn` modules which are essentially thin wrappers around this.
The architecture here is intended to reflect the future sync flow:
1. Begin beatree update, providing the `Store` as a handle. Initiate a sync and give each worker a `SyncAllocator`.
2. Have the beatree update workers call `allocate` and issue commands along an I/O handle.
3. When the workers are concluded, call `SyncFinisher::finish` in the writeout task.
4. Wait for all I/O to conclude.
5. Perform `fsync` on the underlying file descriptors.
> refactor: introduce new Store/SyncAllocator/SyncWriter

- nomt/src/beatree/allocator/mod.rs
Larger increments will get out of the way of the critical path.
> refactor: grow beatree stores by 32MB increments

- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/mod.rs
Like the previous PR, this improves the encapsulation of the leaf stage. And like the previous PR, there is a slight optimization as a result of incrementally applying changes as workers finish.
`fn update` is now dead-simple and just invokes both stages sequentially.
This is also a step towards handling overflow logic inside of workers, but that can come in a later refactoring.
> refactor(leaf-stage): handle overflow inside leaf stage

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/bbn.rs
- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/leaf/store.rs
- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/branch_updater.rs
- nomt/src/beatree/ops/update/extend_range_protocol.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/writeout.rs
- nomt/src/store/sync.rs
This PR modifies the beatree update / sync logic so writes are dispatched while work is ongoing.
Currently, this doesn't optimize or pessimize - it takes exactly the same amount of time as before. Profiles seem to indicate that this is because backpressure on the I/O channel creates some locking/unlocking overhead in the bounded channel.
I will experiment with unbounded I/O channels too, as I'm also seeing this effect in the HT write sequence now that I know what to look for.
Future PRs will:
1. Reinstate the beatree update tests
2. Delete the `beatree/bbn` and `beatree/leaf/store` modules
> opt(beatree): have beatree update issue writes immediately

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/index.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
This updates the tests accounting for the fact that update now submits I/O.
> refactor: reinstate beatree update tests

- nomt/src/bitbox/mod.rs
- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
- nomt/src/seek.rs
- nomt/src/store/mod.rs
- nomt/src/store/page_loader.rs
This PR makes the `IoHandle` submit channel unbounded.
Previously, backpressure was causing threads submitting I/O to park and be woken by the I/O thread when backpressure began.
The concrete downsides:
* The overhead of parking/unparking the threads handling the workload caused inefficiency.
* The I/O threads had to acquire a mutex inside of the channel, which was sometimes contended. Then a further syscall was made. This reduced IOPS.
I suspect this problem was self-reinforcing: waking up senders slowed I/O throughput, which caused more backpressure, causing senders to park more, causing more wakeups to slow down the I/O thread. And so on.
This required some changes in `Seek`, which assumed that the channel itself backpressured.
> opt: use unbounded channels to submit I/O

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/tests.rs
- nomt/src/bitbox/wal/write.rs
This changeset makes the buffer in which we assemble the WAL blob to
grow gradually instead of just allocating a really big amount of virtual
memory at a time. This should not affect performance that much in the
steady state, if at all, but at the same time it would not require
allocating huge virtual memory areas which can actually fail in rare
cases.
> grow wal gradually

- Cargo.lock
- benchtop/Cargo.lock
- nomt/Cargo.toml
- nomt/src/beatree/index.rs
Imbl is a fork of im with several fixes, including something akin to https://github.com/bodil/im-rs/pull/216 .
> refactor: use imbl instead of im, which is unmaintained

- nomt/src/beatree/index.rs
Searching for a range allocates memory, `lookup_prev` doesn't.
> refactor: use get_prev for Index lookup

- Cargo.lock
- nomt/Cargo.toml
- nomt/src/lib.rs
- nomt/src/sys/linux.rs
- nomt/src/sys/macos.rs
- nomt/src/sys/mod.rs
- nomt/src/sys/unix.rs
This is the first step for a serious of refactors.
> chore: introduce sys module

- nomt/src/page_cache.rs
This was originally meant to be an optimization, but with the new `shard_index_for` function, it's faster just to call the `shard_index_for` unconditionally.
> opt: avoid calling RegionContains::contains in page cache update

- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
Many POSIX APIs can return EINTR. Typically, this happens when a signal
is delivered to a thread spending its time in the kernel. The canonical
way to handle this error is to retry running it.
Note that this can only happen before any data is read. Excerpts from
linux man pages for read(2):
EINTR  The call was interrupted by a signal before any data was
read;
macOS READ(2):
[EINTR]            A read from a slow device was interrupted before any
data arrived by the delivery of a signal.
From what I can tell, this also applies to iouring.
> fix: handle EINTR

- nomt/src/bitbox/wal/tests.rs
We create a tempdir and open the file with the O_DIRECT flag.
Surprisingly, nobody ever noticed that, but it shouldn't succeed 
because tmpfs doesn't support O_DIRECT.
> fix: don't use O_DIRECT on tmpfs

- .github/workflows/ci.yml
the time has come. Noticed a lot of time fmt changes are folded into
PRs. This is slightly annoying because after looking at a line for a
couple of seconds you may realize that it's just and only a formatting
change.
If you don't want to deal with this on the CI, I suggest you to install a pre-commit hook that would warn you if you are about to commit an unformatted code.
> ci: run cargo fmt --check

- nomt/src/sys/unix.rs
use the cvt pattern when dealing with this kind of code, which checks
the resulting signed integer to be -1 and if it is requests errno and
converts it to an error.
this will come in-handy later because most of the syscalls we do returns
an error in this form and requires retrying in case of EINTR.
> fix: check EINTR for flock

- .github/workflows/ci.yml
this adds a check that verifies that the nomt crate and
benchtop builds cleanly on darwin.
This is limited to the nomt crate because this is definitely
sketchy and some crates (at the moment of writing it's at
least libfuzzer) do not build.
x86-64 darwin is picked because this is what ubuntu-latest
is running.
> ci: add darwin check

- benchtop/Cargo.lock
- core/src/trie_pos.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/page_cache.rs
- nomt/src/page_diff.rs
Calling `page_is_empty` on every page was very expensive. It's cheaper to have the page-walker detect when pages have been completely cleared.
> opt(merkle): have page-walker precompute whether pages are empty

- nomt/src/beatree/leaf/node.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
The following pr contains all the follow-ups to #529.
One specific thing I would like to ask is an opinion to the introduction of `LeafNode::extract_key`. It is a small abstraction that still requires some conceptual thoughts. The point is: the layout of the leaf node is mostly encapsulated within its module, and inside `keep_up_to`, I was extracting the key from the `cell_pointers`. However, I thought that a modification in the layout of the leaf node could silently break the leaf updater. That's why I added this helper function. In case a layout change happens, the entire `leaf/node.rs` code would be updated, including the way a key is extracted from the cell pointer.
> refactor: follow-up to leaf updater uses binary search

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/bit_ops.rs
This pr not only extracts the shift and copy bits logic a new function(`bitwise_mempcy`), but also includes a slight update: now `bitwise_memcpy` leaves unchanged all the bits that are not part of the copy in the destination
edit. the pr now also includes a replacement of `init` with `start` every time it was not used correctly
> refactor: add bitwise_memcpy

- nomt/src/beatree/leaf/node.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
- nomt/src/beatree/ops/update/tests.rs
Print to stderr the seed used in the branch and leaf stage tests to make the tests easily reproducible locally.
This pr also includes a deletion of some `println`s, see #566 for context
> test: print branch/leaf_stage seed on stderr

- nomt/src/beatree/ops/update/tests.rs
It could happen that a leaf or branch node is not properly encoded,
causing the first key to be larger than the last one.
This could have led to a panic during the validation of the output.
> test: avoid panic if node is not properly encoded

- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
Now, instead of sync handling the concurrency, beatree itself
controlls concurrency.
No functional changes.
> chore: tuck beatree sync coordination inward

- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
Introduces a version number to the manifest file.
Version numbering starts with 1, 0 is an invalid version. Magic
number is set to bytes equivalent to the ASCII string `NOMT`.
This also adds validation rules: invalid magic is rejected. Version
less than 1 is rejected. Also the validation code will reject all versions
above the current one assuming they will introduce incompatibilities.
I anticipate that we can preserve backward compatibility in some cases and
therefore opening db formats with lower version might be possible. If not,
then a validation error should also be returned.
Closes THR-36
> feat: introduce db magic & version

- nomt/src/rollback/mod.rs
- nomt/src/store/sync.rs
Quick change that removes unnecessary result.
> chore: remove unused result

- nomt/src/io/mod.rs
- nomt/src/store/mod.rs
reading from a file that is stored on tmpfs seemingly
returns all zeroes. Disable iopoll if run on tmpfs.
reproduced on linux 5.15 ubuntu.
> fix: disable iopoll on tmpfs

- nomt/src/beatree/leaf_cache.rs
- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
This is super raw; will be refined in later PRs. Let's not merge until the full stack is ready.
The cache is populated when leaves are read and when the workload creates new leaves.
> opt: introduce a leaf cache

- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
Leaf cache eviction and update were blocking the critical path. This PR moves them to a background task.
> opt: move leaf cache update and eviction out of critical path

- nomt/src/beatree/leaf_cache.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
- nomt/src/io/mod.rs
Before the leaf cache, `preload_leaves` was I/O bound, so there wasn't any benefit to parallelizing. Now, a lot of the work is CPU bound as long as most of the items are in the cache, so it makes sense to parallelize.
Also, for every value in the workload we were querying the index for the appropriate leaf twice: once when preloading leaves, and once again during the leaf stage itself. That work was redundant, so this PR introduces `PreparedLeaf` as a solution.
> opt: remove preload_leaves in favor of a preload_and_prepare

- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
the goal of this refactor is to  avoid duplicating
meta write logic. Most of the time, when adding a field
to meta, you need to update it here as well. Not anymore.
also cleans up the store module as well.
> chore: refactor meta creation

- nomt/src/beatree/leaf/node.rs
- nomt/src/beatree/leaf/overflow.rs
- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
- nomt/src/lib.rs
- nomt/src/store/mod.rs
Including the value hash in overflow cells enables us to always obtain the value hash associated with any key just by reading the relevant leaf. This is a pre-requisite for removing leaf-children.
> refactor(beatree)!: include value hash in overflow cells

- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/beatree/ops/update/tests.rs
This introduces a basic read transaction type (not currently used) that is a first step towards enabling a safe asynchronous API for beatree. The immediate motivations are:
1. The removal of leaf children requires us to query many leaves asynchronously during merkle update.
2. Likewise, the rollback log requires us to do the same in order to fetch previous values.
A less immediate but also useful goal is read transactions being used in `Session`s to enable parallel VMs to operate with fewer threads. This is groundwork for that future.
Read transactions don't block commit or `finish_sync` (leaving room for "async sync" in the future), but do block `sync` from beginning. We can expect that sync will _start_ at a natural moment where there are no outstanding read transactions (after a …
> refactor(beatree): introduce a read transaction type

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/branch_updater.rs
This is the first working version of the introduction of binary search within the branch_stage. I'm sure there is still a long way to go for further optimization. At the same time, I have been working on this for weeks and would be happy to receive feedback and use this as a starting point for all future optimizations.
> opt: add binary search in branch updater

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/update/branch_updater.rs
Iterating over all keys in the chunk was extremely expensive; we have enough information to perform these calculations cheaply in the happy path.
In a sample of the previous PR, `body_size_after` took 41% of `branch_stage::run` runtime. In a sample on this commit, it took 1.1%.
> opt: improve body_size_after to avoid O(n) logic

- nomt/src/beatree/ops/update/branch_updater.rs
This is very similar to the previous PR.
After this PR, the branch stage on a DB of 2^26 takes less time than the leaf stage in a workload of 10k transfers.
Before this and the last PR, it was common for the branch stage to take 30-40ms on the same workload. With this PR, it takes at most 6ms.
With a DB of 2^26 and a 10k transfer workload, approximately 19750 leaves and 2500 branches are updated.
In a single-threaded sample, running the leaf stage typically took 65ms and the branch stage took 24ms.
This gives ~3.3us per leaf and 9.6us per branch in this single-threaded example.
> opt: improve BranchGauge::ingest_chunk to avoid O(n) logic

- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/page_pool.rs
- nomt/src/io/unix.rs
This is one of the first steps on the way to reduce the proliferation of FatPage across the codebase. 
The plan here is to gradually switch to Page in the IO subsystem. In the near future, Write and WriteRaw will be merged together.
> opt: write raw operates on page

- nomt/src/beatree/ops/update/branch_updater.rs
The changeset not only includes fixes for how uncompressed separators
are represented through BranchOp, but also contains a refactor
to better encapsulate the update logic of BranchOp.
Note: consume_and_update_until reports the following doc:
```
// If `stop_prefix_compression` has to be called, then the target becomes BRANCH_MERGE_THRESHOLD
// to minimize the amount of uncompressed items inserted in the node.
```
This was never really discussed before, but while working on the tests, I noticed how this was expected by the test `shared_prefix_collapse`. I thought, besides making sense leading to fewer edge cases, to explicitly state the behavior and ensure it effectively happens. It will be tested by multiple tests in follow-up PRs.
> fix: adjust BranchOp handling

- nomt/src/beatree/ops/update/branch_ops.rs
- nomt/src/beatree/ops/update/branch_updater.rs
- nomt/src/beatree/ops/update/mod.rs
The following includes a significant refactor of the branch updater. The main goal was to encapsulate all the logic for branch operation handling elsewhere, in this case in the `BranchOpsTracker`.
I'm not attached to specific names, so suggestions are welcome. I find it extremely interesting how the `BranchUpdater` has been greatly simplified, and as a result, the module's source of errors seems to be drastically reduced.
It is a substantial refactor, and I wasn't able to split it across multiple smaller pull requests. Looking at how many lines changed it seems completely new code, but it isn't. Just most of the logic that was spread around the `BranchUpdter` is logically moved into the `BranchOpsTracker`. The only real change is in how bulk split is handled. It is not something that is …
> refactor: add BranchOpsTracker

- core/src/trie_pos.rs
- nomt/src/merkle/page_walker.rs
`TriePosition::is_first_layer_in_page` was returning a false positive.
`PageWalker::build_stack` wasn't respecting the comment:
> or `None`, if we need to push the root page as well
Tests have been fixed/added to ensure the correct behavior
of the corrected function and the usage of the clear bit in the page diff.
> fix: page_walker and trie_position bugs

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/bitbox/wal/read.rs
- nomt/src/bitbox/wal/tests.rs
- nomt/src/bitbox/wal/write.rs
- nomt/src/lib.rs
- nomt/src/options.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
- nomt/tests/common/mod.rs
- nomt/tests/exclusive_dir.rs
- nomt/tests/extend_range_protocol.rs
- nomt/tests/fill_and_empty.rs
- nomt/tests/last_layer_trie.rs
- nomt/tests/rollback.rs
- nomt/tests/wal.rs
Our sync order of operations is:
1. WAL + beatree shadow pages
2. meta update
3. destructive hash-table writes
4. WAL truncate
specifically, the WAL is for crash consistency in situations after step 2: the beatree has the new values but the hash-table buckets might be incompletely altered.
therefore, a crash _before_ step (2) has completed should not lead to a WAL recovery. This PR fixes and tests this by adding the `sync_seqn` to the WAL and checking during recovery.
> fix(wal): add sync_seqn to WAL and skip recovery when not matching.

- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/mod.rs
- nomt/src/beatree/ops/overflow.rs
This is preparing for non-blocking variants.
> chore: rename lookup to lookup_blocking

- benchtop/src/custom_workload.rs
- benchtop/src/transfer_workload.rs
there are some parts of the code that are inherently non-parallel. This helps with performance a bit.
> chore: reduce benchtop init workload size

- nomt/src/bitbox/mod.rs
- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/src/merkle/worker.rs
- nomt/src/page_cache.rs
- nomt/src/rw_pass_cell/mod.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
There are two reasons to do this:
1. Perf. We copy the pages anyway during sync and it's currently a single-threaded bottleneck. Doing it during `commit` where we have more threads would be best.
2. Overlays. Overlays can't mutate pages in place, so they need to be copied.
I suspect that this will actually be _faster_ than `master` for commit-concurrency > 1. However, I will also benchmark for commit-concurrency = 1 (note: I remove the copies during writeout only further upstack, so the benchmarks will be there)
This seems to obviate the read/write pass stuff, so if perf holds up we should likely just remove those in follow-up PRs.
> refactor: merklize into copied pages

- nomt/src/bitbox/mod.rs
- nomt/src/page_cache.rs
This is a general refactor (good separation of concerns) but also prepares bitbox to receive unowned pages and remove the need to copy before writing.
I also killed the `PageData` struct in `page_cache` , instead opting for `PageMut` and `Page` to wrap `Option<FatPage>` and `Option<Arc<FatPage>>` directly. Because pages are now copy-on-write and need to be explicitly reinsterted into the cache, we don't need to worry about `None` becoming `Some` in one view but not being reflected in the version within the cache.
> refactor: have page cache handle writing page ID rather than bitbox

- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
This adds a `WriteArc` I/O command which writes out of an `Arc<FatPage>`. In the follow-up PR this is used to avoid copying in bitbox writeout.
> refactor: add WriteArc io command

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/writeout.rs
- nomt/src/io/mod.rs
- nomt/src/page_cache.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
This uses the new `WriteArc` I/O command to avoid a page copy when writing to bitbox. This is currently a major bottleneck during `sync`, since these page copies are single-threaded and we now copy pages during merkle commit (needed for overlays).
> opt: do not copy pages before bitbox writeout

- nomt/src/lib.rs
- nomt/src/store/mod.rs
Makes the sync_seqn number accessible. Helps to detect whether a commit succeeded or not.
Closes THR-86
> expose sync_seqn

- .github/workflows/ci.yml
The run cmd line is slightly incorrect. First it specifies --release
and --workspace flags before the test name. The test name is the
first positional argument which makes the arguments following
after it ignored.
However, we are not interested in running tests under loom across
all the workspace, we want to run only rw_pass_cell tests.
To achieve this we pass `-p nomt` to limit the tests to that crate
only. We also pass `--lib` to avoid running external tests (under
`nomt/tests`) because there are no loom tests in there.
> fix(ci): run rw_pass_cell only

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/workload.rs
This changeset changes the key generation so that not every key is random every time. Instead, a key that was already generated will be returned with some probability.
> torture: exercise keys that already were used before

- torture/src/spawn.rs
When the user presses ^C the shell sends the SIGINT
to the entire process group. That is, not only the
supervisor gets SIGINT but also all the agents.
That creates a race: the child dies first and
the supervisor registers it's as a failure and
flags for investigation.
creating it in another pg solves this
> fix(torture): change pgid of the agent

- torture/src/supervisor.rs
otherwise it might feel not responsive.
> chore(torture): move the ^C log to where it happens

- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
Clarify that the utilization metrics are spot, i.e. point in time. So the user
don't think that they can obtain a single object and call the occupancy method.
> chore: clarify that the utilization is spot

- nomt/src/io/mod.rs
This was needed when the IoKind enum contained raw pointers to the pages.
Nowadays it doesn't.
> chore: remove unused unsafe impl.

- nomt/src/beatree/branch/node.rs
The structure of a branch node is the following:
+ bbn_pn: u32
+ n: u16
+ prefix_compressed: u16
+ prefix_len: u16
+ cells: u16[n]
+ prefix: bitvec[prefix_len]
+ separators: bitvec
+ padding
+ node_pointers: leaf_node_page_number[n]
The unsafety in the module is driven by reading `cells` and `node_pointers` as slices with the number of elements given by `n`. Ensuring that `n` leads to a read within the bounds of the `FatPage` will make the read panic instead of some other errors.
Every other read passes through an access of the `FatPage`, so any out of bounds access will lead to a panic.
Closes THR-63
> feat: tighten read of branch node

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/writeout.rs
This changeset does change the behavior.
Before:
1. we did not do fsync after truncating WAL in bitbox post meta.
2. we did not do fsync after truncating WAL after recovery.
Now:
1. We still do **not** fsync after truncation in bitbox post meta.
2. We now do fsync after truncating WAL after recovery.
The main motivation of this changeset is to document the existing bitbox post-meta behavior.
> chore: comment the bitbox truncate WAL routine

- torture/src/supervisor.rs
Upon exit, regardless if via ^C or reaching number of flags, display all the
flags collected so far.
> torture: print flags upon exit

- nomt/src/lib.rs
- nomt/src/overlay.rs
This defines the `Overlay` types. I tried to make it passably fast at an algorithmic level and will follow up with integrations!
> feat: overlay type definitions and operations

- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/tests.rs
What this pr implements is a function to enforce that the separator of the first leaf in the beatree is all 0.
The reason for opting for a new function is to avoid adding complexity to the leaf_stage logic. Carrying around information about the first leaf would have required a lot of modifications here and there. Now, instead, that rule is enforced by only the new function and the `unwrap_or` within the `LeafUpdater::separate` function. Additionally, this edge case is very unlikely, and the function will, for the most part, return after the first check. The goal was to minimize the impact on the critical path and reduce code complexity while maintaining the rule's validity.
Closes THR-91
> fix: first leaf mut have a separator of all 0

- benchtop/src/nomt.rs
- examples/commit_batch/src/lib.rs
- examples/read_value/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/lib.rs
- nomt/src/overlay.rs
- nomt/tests/common/mod.rs
- nomt/tests/rollback.rs
- torture/src/agent.rs
These are all unimplemented at the moment, but gives a hint of what the API would look like.
I do think there is a combinatorial explosion (especially if we split out `sync` in the future). This is just an initial approach to get started and then we can do a full API pass later to make it nice.
> feat: update* functions in NOMT API

- nomt/src/bitbox/ht_file.rs
- nomt/src/store/mod.rs
- nomt/src/sys/linux.rs
iopoll is capricious. It requires the target fs to be block-y or
similiar to be polled. If it is not the case, then you will get
ENOSUPP from one of CQEs coming from io-uring.
this changset disables iopoll for any fuse-backed filesystems,
restructuring the way we do the check along the way.
> fix: not use iopoll on fuse

- benchtop/Cargo.lock
- benchtop/Cargo.toml
- benchtop/src/main.rs
It might be interesting to know how much memory the benchtop
process consumed at its peak, so print it at the end of
execution.
> benchtop: print max rss

- nomt/src/lib.rs
- nomt/src/rollback/delta.rs
- nomt/src/rollback/mod.rs
- nomt/src/rollback/tests.rs
This also moves rollback delta creation to `update_inner` and rollback delta committing to `commit_inner`.
> refactor: split rollback delta creation and commit

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/workload.rs
The following feature was very easy to implement and highly effective as it significantly increased crash occurrences during sync. 
With `trickfs`, this issue will be secondary, as it will allow actions such as crashing when writing to a specific memory area or file. Therefore, I'm fine if you prefer to close this PR and wait for `trickfs`!"
> feat(torture): crash after average commit time

- nomt/src/beatree/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/overlay.rs
- nomt/src/page_cache.rs
- nomt/src/rollback/delta.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
I don't love the amount of cloning we do, but we can optimize that later.
> feat: flesh out overlay update/commit functions

- nomt/src/bitbox/mod.rs
- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/src/merkle/worker.rs
- nomt/src/overlay.rs
- nomt/src/page_cache.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
With this PR, I overhauled the merklization pipeline (page cache / page walker / bitbox) in preparation for overlay changes.
Significant changes:
- Page cache now only stores completely clean pages, i.e. pages submitted for write, and updates are outside of the critical path.
- Page cache pages are no longer an `Option`. Either the page is allocated, or it is not. This simplifies some logic.
- Introduced a `DirtyPage` struct which tracks bucket information (including buckets not yet allocated)
- Introduced a `PageSet` used by `Seek` / `PageWalker`. The page walker, instead of drawing on the page cache directly, will only take pages from the `PageSet`. It is populated by `Seek`. In the future, `Seek` will draw on the live overlay, the page cache, or the disk in order to populate the page …
> refactor: page cache / merklization / bitbox overhaul for overlays

- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/seek.rs
- nomt/src/merkle/worker.rs
Here we wire up overlays with merklization. The merkle logic now attempts to load the page from the overlay (if present) and only then falls back to the page cache (and then disk).
> feat: use overlay as page source in merklization

- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/worker.rs
The `PageSet` created for overlays broke warm-ups and this PR fixes it.
Prior to overlays, warmed up pages were inserted into the global page cache and the page walker drew from it, so the pages were guaranteed to be available to update workers.
However, with the `PageSet` refactor we needed a way for the working page-set gathered by warm-ups to be made available to the workers. I opted to do that in this PR by creating a wrapper around an `Arc<HashMap>` that stores all the warmed-up pages, and pass this to the workers as a fallback.
> fix: warm-up page set creation

- torture/src/agent.rs
- torture/src/supervisor/comms.rs
- torture/src/supervisor/workload.rs
Make sure that any reverted changes did not alter
already present values. To do this, compare them with
the values of the previous state maintained by the supervisor.
> feat(torture):reverted changeset on previous state

- benchtop/src/backend.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- nomt/src/overlay.rs
I ran some benchmarks (details in slack) on the overlay work in this stack.
I observed performance at about par (43 vs 45k TPS) on master in the base case. But when running with overlays, I observed faster performance (70k TPS for a single overlay - a bit baffling, will discuss offline but seems to have uncovered a route for additional optimization)
> feat(benchtop): add overlay support

- torture/src/supervisor/workload.rs
Use hex values for displaying KVs, because dec looks very ugly.
> feat(torture): print hex values

- nomt/src/bitbox/mod.rs
WAL recovery wrote the nodes into pages, but not the page ID.
That meant that fresh pages which are recovered only from the WAL would not be probeable and would be treated as misprobes, silently losing data. The fix is to set the page ID on WAL recovery.
> fix: label pages in WAL recovery

- torture/src/agent.rs
Right now the values are just printed unit-less.
> fix(torture): print elapsed times in ms

- torture/src/supervisor/comms.rs
- torture/src/supervisor/workload.rs
Spawning a blocking task to handle the reception of the message is a workaround to make it possible to handle large overflow values.
Using the standard `timeout(self.shared.timeout, rx).await??;` does not work, it hangs when the expected value to be received is larger than 15KiB.
The problem seems to be strictly related to the interaction between `tokio::time::timeout` and `tokio::sync::oneshot::Receiver`.
A simple code like the following perfectly works.
```rust
let message = loop {
tokio::time::sleep(Duration::from_millis(1)).await;
if let Ok(something) = rx.try_recv() {
break something;
}
};
```
It seems that the `Future` implementation of `tokio::sync::oneshot::Receiver` switches from being non-blocking to blocking if the size of the message gets bigger than 15KiB.
But I also found …
> fix(torture): handle large overflow values

- nomt/src/lib.rs
Right now Metrics is not public and, even though it's it exposed through
[`Nomt::metrics`] it is not really useable.
Ideally, we should expose Metrics. However, right now Metrics is not really good
fit for the end-user API and requires rework.
Until then — hide it from the public API.
> chore: doc(hidden) on Metrics

- torture/src/supervisor/cli.rs
- torture/src/supervisor/workload.rs
Together with `ensure-snapshot` they cover two different ways of
checking the validity of the state after a crash or a rollback happened.
`ensure-snapshot` checks the entire state while `sample-snapshot` just
checks a random subset of the state.
> feat(torture): add `sample-snapshot` option

- torture/src/agent.rs
- torture/src/supervisor/workload.rs
Previously, the check was made immediately after respawning the child,
which implied a check of the snapshot over a non-up-to-date
`state.last_snapshot()`, leading to incorrect checks.
> fix(torture): move snapshot check

- nomt/src/merkle/page_walker.rs
After removing leaf children, it is no longer possible for the page walker to revisit a page.
This previously occurred when we:
1. Removed leaf children (push, pop)
2. Wrote more nodes into the page afterwards (push)
But now all pages are visited exactly one time.
> refactor: remove unneeded branch in PageWalker::down

- nomt/src/beatree/iterator.rs
- nomt/src/io/fsyncer.rs
- nomt/src/lib.rs
- torture/src/supervisor/workload.rs
Since we are going to rehaul the API and docs anyway I only did a halfassed pass to silence the warnings in order to disallow them in the next PR.
> fix: fix up errors coming from rustdoc

- .github/workflows/ci.yml
Make the errors, such as broken links and other stuff as errors. We don't want
master printing warnings when building docs, as we don't want dangling links.
> feat(ci): strict rustdoc

- torture/src/supervisor/cli.rs
- torture/src/supervisor/workload.rs
Define a `rollback-bias` argument which defines the probability
of executing a rollback instead of a commit.
Add then `rollback-crash-bias` and `commit-crash-bias`,  two
arguments to define the probability of causing to crash respectively
the rollback or the commit when they would be performed.
This is based on what @pepyakin pointed out [here](https://github.com/thrumdev/nomt/pull/706#discussion_r1922495335)
> refactor(torture): probabilities handling

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/cli.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/workload.rs
+ More sophisticated value generation.
+ Use the `max_rollback_blocks` cli argument as nomt option for `max_rollback_log_len`.
+ More sophisticated new key generation.
To prove my claim on the amount of probabilities for a given amount of shared bytes, you can check some tests I did [here]( https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5aaa317ab9e7e2bc62662ffe415e837d).
> chore(torture): address multiple left todos

- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/src/merkle/worker.rs
The motivation here is to avoid specifying whether merklization will target an overlay or not at the beginning of a session. This frees up more changes to the API later.
> refactor: defer bucket info dependent allocation to post-merklization

- benchtop/src/nomt.rs
- examples/commit_batch/src/lib.rs
- examples/read_value/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/lib.rs
- nomt/tests/common/mod.rs
- nomt/tests/rollback.rs
- torture/src/agent.rs
This is a first stab at reworking the API of NOMT. For initial review and as a base for discussion.
Motivation:
1. Future-proofing. We should be able to add more parameters to commits and sessions without causing a breakage.
2. Limit combinatorial explosion of options. `update`/`commit`/`prove` led to 4 separate functions on NOMT for all their combinations. Adding additional variants would have caused a further explosion.
3. Allow multiple sessions to exist. Now that the page cache only reflects the on-disk state, there is no reason not to have multiple sessions existing at once, as long as there is only ever a single writer.
Limitations of this PR:
- splitting `finish_session` and `commit_finished` is a bit clunky.
- needs a locking scheme to make writes safe
- needs a check to ensure …
> refactor: rework session API

- examples/commit_batch/src/lib.rs
- examples/witness_verification/src/main.rs
- nomt/src/lib.rs
- nomt/src/overlay.rs
- nomt/tests/add_remove.rs
- nomt/tests/common/mod.rs
- nomt/tests/compute_root.rs
- nomt/tests/fill_and_empty.rs
- nomt/tests/overlay.rs
- nomt/tests/rollback.rs
- nomt/tests/witness_check.rs
This introduces a newtype for the root of the trie for the public API. It comes with pretty-printing and the `is_empty` utility function.
> refactor: introduce Root type for public API

- nomt/src/lib.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
In case the database encounters an IO error during the commit, there
will be some intermediate partial changes to the database.
It is possible to recover from them, however, in the interest of
reducing complexity, we mark the database as poisoned and reject any
further modification attempts. That allows NOMT to avoid spreading the
recovery logic all around but concentrate it in the startup logic.
> feat: poison

- nomt/src/beatree/mod.rs
- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/writeout.rs
- nomt/src/rollback/mod.rs
- nomt/src/seglog/mod.rs
- nomt/src/seglog/segment_rw.rs
- nomt/src/store/meta.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
This reduces the scope of errors that could be thrown by the components
deliberately.
> chore: migrate lower-level components to io err

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/workload.rs
+ update docs
+ `scheduled_rollback` can either be forced to crash or not,
stop treating rollback and rollback crash as two different things
+ handle delays with `Duration`s
> refactor(torture): address various follow-ups

- nomt/src/lib.rs
- nomt/src/overlay.rs
- nomt/tests/prev_root_check.rs
Without this, it was possible to silently corrupt the database when writing conflicting sessions.
> feat: add a prev_root check when committing

- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/leaf_stage.rs
If the leaf or branch updater just returned a `NeedsMerge`
do not try to answer within the range extension protocol.
> fix: extend range, do not respond during merge

- nomt/src/beatree/mod.rs
This was supposed to be tackled by 594f8e.
> chore: remove stale todo

- Cargo.lock
- Cargo.toml
- README.md
- trickfs/Cargo.toml
- trickfs/README.md
- trickfs/src/lib.rs
- trickfs/src/main.rs
Introduces trickfs, a fuse filesystem for made for failure injection.
> torture: trickfs

- Cargo.lock
- Cargo.toml
- README.md
- trickfs/README.md
- trickfs/src/main.rs
- trickfs/trickmnt/Cargo.toml
- trickfs/trickmnt/src/main.rs
adds a binary target called `trickmnt` to quickly mount a trickfs
locally.
> trickfs: add trickmnt

- Cargo.lock
- torture/Cargo.toml
- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/cli.rs
- torture/src/supervisor/mod.rs
- torture/src/supervisor/trickfs.rs
- torture/src/supervisor/workload.rs
and as the first thing to test, just toggle on the ENOSPC
from run to run.
> feat(torture): integrate with trickfs

- nomt/src/seglog/mod.rs
Otherwise it leads to gaps in IDs and the rollback log is rather
sensitive to those when it comes to recovery.
Fixes:
```
Error: Error during scanning segment /tmp/torture-CttwEt-workload-0/nomt_db/rollback.0000000001.log
Caused by:
IDs are not ordered: this 10, expected 3
```
> fix: increment ID only append succeeded

- torture/src/agent.rs
- torture/src/logging.rs
- torture/src/message.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/workload.rs
when the database gets ENOSPC it becomes poisoned and it is required to
recreate it in order to perform further changes to the database.
this commit does that.
To get there, it was necessary to split initing of the agent (happens at
most once per agent process) from opening a NOMT instance (can happen
multiple times). Note that opening carries the fields such as
`bitbox_seed` and `rollback` which might not be useful each time. This
is by design, because we might want to test what happens if you do
change it from open to open.
> fix(torture): handle poisoning

- trickfs/src/lib.rs
Actually, we can expect no entries at all when removing a dir. But let's check
that anyway and return a special error reserved for such cases.
> fix(trickfs): nonempty rmdir

- trickfs/src/lib.rs
describes the what and how is achieved by trickfs.
> chore(trickfs): add rustdoc

- benchtop/src/nomt.rs
- core/src/proof/multi_proof.rs
- core/src/proof/path_proof.rs
- core/src/trie.rs
- core/src/update.rs
- examples/witness_verification/src/main.rs
- fuzz/fuzz_targets/api_surface.rs
- nomt/src/lib.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/tests/add_remove.rs
- nomt/tests/common/mod.rs
- nomt/tests/compute_root.rs
- nomt/tests/rollback.rs
- nomt/tests/witness_check.rs
1. Export a couple more things from the NOMT crate root that make it possible to implement a NodeHasher
2. Make determining the node kind a function of the NodeHasher, and give the NodeHasher the responsibility of labeling nodes.
> refactor: put node hasher in charge of labeling nodes and determining kinds

- Cargo.lock
- benchtop/Cargo.lock
- nomt/Cargo.toml
- nomt/src/bitbox/mod.rs
A seeded twox is suitable for this purpose - each node will have its own map. While it may be possible to convince publicly-accessible RPC nodes to leak information that enables a HashDoS, it seems unlikely for sequencers to leak it. 
Furthermore, the complexity of such an attack is limited by the fact that the inputs are Page IDs. In order to write to a particular page ID, the attacker would first need to create accounts (against a cryptographic hash function) that land in those pages. 
Computing the blake3 hash of each written bucket was quite CPU-intensive, and so using twox ought to be much faster.
> opt: [BREAKING] use twox_64 for bucket hashing

- nomt/src/lib.rs
- nomt/src/task.rs
Utilities used to have an error handling approach that follows two rules:
+ Fail fast: If a panic occurs in a worker thread, the main thread waiting
for that worker to complete will also panic, printing the original panic payload.
+ Forward errors that do not depend on non-mt logic.
The utilities do not cover any type of context propagation. I tried many solutions to add context to the panics and error results of the task, but I couldn't find a proper way to provide context for both in a nice way. Open to suggestions! 
I decided to push the utilities anyway because with just a few lines of code they achieve the desired goals and simplify the codebase. You will see this in the next PR on this stack.
> feat: add `spawn_task` and `join_task` utilities

- nomt/src/bitbox/mod.rs
The removal of the `SyncError` enum is related to two things:
1. In Bitbox, there are two tasks that separately return the two variants of the enum. Thus, we don't really need to wrap them under the same umbrella.
2. `torture` couldn't downcast the error to ENOSPC because it was wrapped in that enum. Just converting it to `anyhow` makes it possible instead!
> feat: bitbox propagates errors during begin_sync

- nomt/src/rollback/mod.rs
- nomt/src/store/sync.rs
Moving from `Condvar` to `crossbeam-channel`s didn't bring any performance regression
> feat: rollback propagates errors during begin_sync

- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
Mainly this changeset makes the io-uring workers exit when the command
rx channel hung up, instead of just spinning endlessly.
Additionally, this makes sure that the page pool is retained until the
very end of each io workers' lifetime. This ensures that there is no
use-after-free wrt to pagepool's buffers.
> feat: graceful shutdown IO workers

- nomt/src/rollback/mod.rs
when `self.shared.max_rollback_log_len` is reached and rollback delta
needs to be pruned from the front, `prune_to_new_start_live` will be the
`RecordId` just after the oldest delta in memory, thus `pop_front` is required.
Closes THR-118
> fix(seglog): `pop_front` in memory log when pruning

- nomt/src/bitbox/mod.rs
- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/seek.rs
- nomt/src/merkle/worker.rs
- nomt/src/store/mod.rs
- nomt/src/store/page_loader.rs
Also include some changes to ensure that every I/O error
is correctly propagated, while everything else causes a panic.
> feat: warm_up thread propagates errors

- nomt/src/bitbox/mod.rs
- nomt/src/io/mod.rs
- nomt/src/merkle/worker.rs
Accessing page_pool via IoHandle is convenience but is a poor
discipline. I've tried to do some refactoring on IoPool and IoHandle and
noticed that it's kind of complicated because those things tie us up. At
the same time it is unnecessary. I decided to scrap the refactor for
now, but decided to salvage this part.
> chore: page pool discipline

- core/src/page_id.rs
- nomt/src/page_cache.rs
This puts all pages with level <= 3 into a "fixed level cache" hash-map.
Cache eviction will never remove these pages and they can only be removed if the page itself is deleted.
This will be followed up by a PR for prepopulation.
> refactor(page_cache): introduce a sub-cache for merkle pages below a fixed depth

- nomt/src/lib.rs
- nomt/src/merkle/cache_prepopulate.rs
- nomt/src/merkle/mod.rs
- nomt/src/options.rs
This prepopulates the 3 upper levels of the page cache (to be made configurable in a follow-up) with a simple recursive algorithm.
Default is false.
> feat: page cache upper level prepopulation

- nomt/src/rollback/mod.rs
- nomt/src/store/sync.rs
Within the `rollback` module, `SyncController::writeout_start` does
not need to be spawned within another thread.
> refactor: avoid new thread for writeout_start

- nomt/src/lib.rs
- nomt/src/options.rs
- nomt/src/page_cache.rs
This allows the user to choose how many upper levels of the page tree to keep permanently in the cache and make the RAM vs. I/O tradeoff appropriately for their use-case.
> feat: make page cache upper levels configurable

- nomt/src/io/linux.rs
Hint the kernel that a single task will submit requests.
> opt: use io_uring `single_issuer` feature

- nomt/src/rollback/mod.rs
- torture/src/supervisor/workload.rs
When a rollback is going to erase all the commits,
`rollback_start_live` will need to be equal to `pending_truncate`.
> fix: adjust `rollback_start_live` update

- benchtop/Cargo.toml
- benchtop/src/backend.rs
- benchtop/src/main.rs
This'll avoid the need to compile large dependencies like RocksDB when building benchtop exclusively for testing NOMT.
> refactor(benchtop) make sp-trie/sov-db features of benchtop

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/workload.rs
The unification of the two has the side effect of handling
ENOSPC errors also for commits that are expected to crash.
> feat(torture): unify exec commit and commit crash

- torture/src/supervisor/workload.rs
The unification of the two has the side effect of handling
ENOSPC errors also for rollbacks that are expected to crash.
Closes THR-110
> feat(torture): unify rollback and rollback crash

- nomt/src/store/sync.rs
Incrementing `sync_seqn` right away within the sync function lead to a scenarion where if an error occurred whithin the `sync` process the nomt instance would get poisoned, but the same instance if queried would return the following `sync_seqn` which was never applied.
What did in this pr I'm not sure if solves entirely the problem, maybe it just moves it in a less painful place (that makes torture to work fine).
Updating it after having update the Meta means that we reflect the state on disk, but if a failure occur during the write of the ht the instance get poisoned, the sync_seqn fetch from the same instance would be correct but it would not be able to read a correct state because there would be a pending WAL batch to be applied to the ht.
> refactor: increment `sync_seqn` after meta update

- nomt/src/beatree/allocator/free_list.rs
Update the length of the free list and fragmented bool when there are only pop operations in a commit and no push operations.
Closes THR-120
> fix: update free list data when no push happens

- Cargo.lock
- torture/Cargo.toml
- torture/src/agent.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/mod.rs
- torture/src/supervisor/pbt.rs
- torture/src/supervisor/workload.rs
To aid debugging cases where the agent got deadlocked (or just timed
out), print the backtrace of every thread of the agent process.
This PR removes dumpable(false) so the caveat might apply. We need the agent process to be dumpable because otherwise we cannot trace it and no debugger can be attached.
> feat(torture): if agent hangs print its bt

- torture/src/supervisor/workload.rs
This PR fixes the issue when the workload might error out because of the
Broken Pipe error. This is unmasked by the previous PR in the stack.
The error is that the rr is not reloaded for sampling/checking the
snapshot applied/not applied after a crash. Instead the rr of the dead
process was used.
This fix comes with a refactor where we store the rr in a field and keep
it synchronized with the agent. This seems to be an easier task than
trying to keep from not reloading it at the right time.
> fix(torture): use the right rr

- torture/src/supervisor/comms.rs
The PR downstack makes this workaround unnecessary.
> fix(torture): don't use blocking recv anymore

- nomt/src/beatree/allocator/mod.rs
grow did not extend the file in case it was already a multiple of the
batch. This change ensures additional space is always allocated.
credit for bug identification goes to gab.
> fix: fix grow in allocator

- torture/src/agent.rs
- torture/src/main.rs
- torture/src/panic.rs
- torture/src/supervisor/mod.rs
Add utilities to handle panics (`Box<dyn Any + Send>`) and forward
them to the supervisor when they happen within the agent.
> fix/feat(torture): handle panics

- Cargo.lock
- torture/src/supervisor/comms.rs
- torture/src/supervisor/workload.rs
- trickfs/Cargo.toml
- trickfs/src/latency.rs
- trickfs/src/lib.rs
- trickfs/trickmnt/src/main.rs
The following pr introduces 'Latency Injection' within `Trickfs`. This can be triggered by the `TrickHandle`, and if triggered, every `trickfs` operation will be subject to a scheduled reply after a certain delay.
Notes:
1. In order to deal with latencies, the timeout for waiting for agent replies needed to be increased, as sometimes there were quite big delays.
2. Two of the most crucial `trickfs` operations are read and write, which I tried to keep simple while injecting latencies. For writes, they happen immediately but the reply of things getting written is scheduled. The same applies to reads, where things are copied into the scheduled reply. This latter part introduces some latency by itself, but it does not significantly impact the code with lifetimes or check if memory got …
> feat(torture): latency injection

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/controller.rs
Update the `OpenPayload` to contain all the open options that nomt supports.
> feat(torture): agent more granular configuration

- torture/src/supervisor/mod.rs
- torture/src/supervisor/resource.rs
- torture/src/supervisor/workload.rs
Currently, `ResourceAllocator` assigns random portions of disk space and memory to workloads, while ensuring that everything stays within well-defined boundaries.
`ResourceAllocator` makes it easy to customize the resource allocation algorithm by simply modifying the `alloc` method!
> feat(torture): add resource allocator

- torture/src/supervisor/config.rs
- torture/src/supervisor/mod.rs
- torture/src/supervisor/workload.rs
Workload logic and its configuration were previously mixed together. Now the goal is to not require the user to specify all features that should be tested. Instead, a more complex testing mechanism should be able to generate workload configurations, grouping all features in one place makes it easier and logically simpler to create and use this configuration by the supervisor.
> refactor(torture):separate workload and its config

- torture/src/supervisor/config.rs
- torture/src/supervisor/workload.rs
During the generation of a changeset, the items can be
updates, deletions or insertions of new items.
This pr moves from a configuration in which a bias
was associated with 'delete' and 'new_key'
to assigning weights to all three options.
> refactor(torture):from bias to weight in changeset

- nomt/src/lib.rs
As well as handy `AsRef<[u8]>` and `From<[u8;32]>`
> feat(nomt): enable `borsh` for `nomt::Root`

- torture/src/supervisor/config.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/workload.rs
This pr brings `torture` to a proper multi-workload executor functioning state.
Everything required to execute and debug multiple workloads should be in place. Now, follow-up PRs will contain all the workload configuration generation because currently, they are hardcoded.
> feat(torture): use workload config for OpenPayload

- Cargo.lock
- Cargo.toml
- benchtop/Cargo.lock
- benchtop/Cargo.toml
- core/Cargo.toml
- nomt/Cargo.toml
Issue described in #850
Resolves #850 
This is more of exploratory PR to understand what was original reason to lock it, and if this problem is still present now
> chore: remove borsh version limit

- torture/src/supervisor/cli.rs
- torture/src/supervisor/mod.rs
- torture/src/supervisor/resource.rs
Adds flags to specify the maximum amount of disk and memory that torture can use,
and also forces the workload to use more space instead of selecting uniformly
between 0 and the available amount
> refactor/feat(torture): resource usage

- torture/src/supervisor/resource.rs
On macOS, `libc::fsblkcnt_t` has a type different from the ones found on Linux.
That is, at least on aarch64-apple-darwin. Haven't digged deeper.
> fix: macOS torture type mismatch

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/comms.rs
- torture/src/supervisor/config.rs
- torture/src/supervisor/resource.rs
- torture/src/supervisor/workload.rs
Estimate the number of items that bitbox and beatree can store to avoid reaching Bucket or Resources Exhaustion. 
To have a proper estimation, I had to remove the custom key distribution, otherwise, the number of expected pages was not easily estimable.
Now you can run the torture swarm testing with the following command: `cargo run --release -p torture -- swarm -f 10 --max-disk 70 --max-memory 80`.
If a run workload fails, it can be repeated with `cargo run --release -p torture -- run <SEED>`, and optionally with the flags `--assigned-memory` and `--assigned-disk`. They are optional because the error might or might not depend on the constraints over resources.
Seed and assigned resources are printed in the `InvestigationFlag`.
> fix(torture): space usage

- Cargo.lock
- Cargo.toml
- benchtop/Cargo.lock
- core/Cargo.toml
- core/src/hasher.rs
- nomt/Cargo.toml
In Sovereign SDK we use `digest` as generic way to reprsent different hashers. So SDK itself does not depend on particular hasher implementation:
```
pub trait CryptoSpec {
type Hasher: digest::Digest<OutputSize = digest::typenum::U32>;
// The rest is omitted
}
```
This PR adds blanket implementation of `BinaryHash` for all Digest with matching output size.
> Use `digest` crate for Blanket implementation of `BinaryHash`

- nomt/src/lib.rs
Sovereign SDK operates on `Session` and `FinishedSession` and it needs access to prev_root to pass it to ZK guest.
I am happy to change location of it, but this method is needed for the integration.
Please let me know if there's any issue of exposing it.
> Expose prev_root() getter for Session

- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/worker.rs
- nomt/src/metrics.rs
Add a feature that counts the number of leaves
in each subtree on a bitbox page.
This pr also introduces two new metrics to keep track of how many pages were elided and how many were actually created or modified.
> feat: count merkle leaves in ht pages

- core/src/page_id.rs
- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/read.rs
- nomt/src/bitbox/wal/tests.rs
- nomt/src/bitbox/wal/write.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/src/merkle/worker.rs
- nomt/src/page_cache.rs
This PR introduces *page elision*, which aims to reduce the space consumption of the hash table. Each HT bucket/page stores a root-less binary tree of depth 6, and page elision means that a page (and its children) is not stored in the hash table if the root-less binary tree contains fewer than a certain number of Merkle leaves. Pages that are elided are then reconstructed on the fly when needed, utilizing the btree to fetch all required values.
The page walker was modified to allow for page reconstruction in a way that minimizes the impact on the codebase and reuses most of the code from the previous PageWalker state. I tried many solutions, but each of them seemed to lead to messy outcomes, with a lot of code duplication. For now, this works, and it was not such an intrusive modification …
> feat: page elision

- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/src/page_diff.rs
Pages that get promoted from reconstructed to updated
are written to disk. However, if the process fails, the WAL only
contains the diffs of updated nodes and not all the nodes,
along with the just reconstructed ones.
This adds the reconstructed nodes to the page diffs as well.
> fix: reconstructed nodes in the recovery process

- torture/src/supervisor/resource.rs
- torture/src/supervisor/workload.rs
This pull request fixes spelling errors in comments across multiple files:
- In torture/src/supervisor/resource.rs: Fix typo in comments about file availability
- In torture/src/supervisor/workload.rs: Fix typo in crash delay documentation
These changes improve code readability and documentation quality without affecting functionality.
> Fix typos in comments

- nomt/src/lib.rs
It simplifies code for structs that only hold Nomt, but don't use it.
Please note that effective boundary remains, but it is only on `impl` blocks
> Removes bound from Nomt struct

- nomt/src/lib.rs
Where it is not needed.
Simplifies client code by removing a lot of trait boundaries.
Similar to https://github.com/thrumdev/nomt/pull/881
> Remove `HashAlgorithm` from Session struct and impl block

- torture/src/supervisor/config.rs
- torture/src/supervisor/workload.rs
Removes following warnings, when built on macos:
```
warning: unused variable: `seed`
--> torture/src/supervisor/workload.rs:211:9
|
211 |         seed: u64,
|         ^^^^ help: if this is intentional, prefix it with an underscore: `_seed`
|
= note: `#[warn(unused_variables)]` on by default
warning: field `trickfs` is never read
--> torture/src/supervisor/config.rs:106:9
|
46  | pub struct WorkloadConfiguration {
|            --------------------- field in this struct
...
106 |     pub trickfs: bool,
|         ^^^^^^^
|
= note: `WorkloadConfiguration` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
= note: `#[warn(dead_code)]` on by default
```
> Add conditional allow for non linux targets

- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/worker.rs
- nomt/src/metrics.rs
- nomt/src/page_diff.rs
As mentioned here https://github.com/thrumdev/nomt/pull/859#discussion_r2035107366, the page elision metrics are not particularly helpful. Understanding whether the feature was effectively eliding pages was only important initially to understand the correctness of the feature.
> refactor: remove page elision metrics

- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
Explicitly describe some duplication of work performed by the page reconstruction process
within the seeker, while simultaneously reducing it by checking if a page has already
been reconstructed before starting the page reconstruction.
A little duplication of work is acceptable because solutions to avoid it have more overhead
than simply performing the task. Benchmarks showed that on a 2^28 database with large commit sizes,
200k, where it is more likely that two requests share the same elided pages),
only 0.1% of elided pages had items collected twice.
> refactor/fix: page elision duplication of work

- core/src/proof/multi_proof.rs
So it can be passed over to ZkVM.
> Adds serialization (borsh & serde) to `MultiProof`

- core/src/proof/mod.rs
- core/src/proof/multi_proof.rs
- core/src/proof/path_proof.rs
- core/src/update.rs
This turned out more involved than I expected.
The `VerifiedMultiProof` has been extended with a `Vec<VerifiedBisection>` that keeps tracks of all the bisections and upper sibling ranges. This is used to recover all needed siblings.
The core of this operates quite similarly to the existing `verify_update`:
1. loop through all terminals (ascending)
2. apply any needed changes to terminals based on `ops` as we go
most of the complexity is in gathering the necessary siblings and making sure they are available. for that I've introduced a helper struct `CommonSiblings`.
I added a few tests, including one which explicitly loads the bisection logic.
Runtime is linear in the number of multiproofs, assuming an average depth per branch. 
This algorithm, as written, does reproduce some of the work …
> feat: introduce a verify_multi_proof_update

- nomt/src/lib.rs
- nomt/src/rollback/mod.rs
- nomt/src/rollback/reverse_delta_worker.rs
- nomt/src/rollback/tests.rs
Rollback delta workers each require 2 paired tasks ("run" and "completions") to run on a threadpool which has only 2 threads. Both tasks must be run to prevent deadlock.
When there were multiple sessions (>2), it was possible for the threadpool to fill up and stall such that there were only unpaired "run" and "completions" tasks, which would then never finished.
My fix here is to rewrite the code so we don't need a second task, but run it all on one task.
I also force them to join when dropped.
Still, the behavior isn't ideal when there are many threads running sessions concurrently. I'd recommend increasing the thread-pool size. This shouldn't lead to deadlocks, but maybe suboptimal performance or weird scheduling artifacts.
> Fix rollback deadlock caused by occupying all threads

- nomt/src/options.rs
So it can be printed by client apps and will be easier to debug
> Derive `Debug` on options.

- .github/workflows/bench.yml
- .github/workflows/ci.yml
Maintenance update to actions/checkout@v5 to align with the current runner stack (Node 24); nothing else modified.
Release notes: https://github.com/actions/checkout/releases/tag/v5.0.0
> CI: migrate workflows to checkout v5
