thrumdev/nomt

- nomt/src/lib.rs
- nomt/src/page_cache.rs
This improves QoL while profiling.
> name threads

- core/src/page_id.rs
unused after page ID iterator rewrite
> chore: remove unused import

- core/src/proof.rs
- nomt/src/lib.rs
The actual data needed for "WitnessedOperations" is up in the air, so consider this a dummy.
In any case, we can do proving based on this alone.
> feat: witness generation

- core/src/update.rs
- nomt/src/lib.rs
I updated the `update` API to not require that the user splice in dummy insert operations to preserve leaves. It was error-prone and confusing.
And in fact, we already had to partition the write space by the terminal node in `commit_and_prove`. So there was no benefit.
> refactor: improve update API

- nomt/src/store.rs
Without this the database is going to fail.
> add LEAF_CF as a column

- Cargo.lock
- nomt/Cargo.toml
- nomt/src/lib.rs
- nomt/src/store.rs
This pull request updates the dependencies for byteorder to version 1.5.0 and fxhash to version 0.2.1. It also includes changes in the Cargo.toml and src/lib.rs files to reflect the updated dependencies and code modifications related to these dependencies. The update aims to enhance performance and compatibility with the latest versions of these crates.
---
> bring back Session

- nomt/Cargo.toml
- nomt/src/lib.rs
- nomt/src/rw_pass_cell.rs
See the documentation. Will be used in the following commits.
> introduce rw-pass-cell

- .gitignore
> chore: gitignore samply profiles / test DB

- nomt/src/lib.rs
during warmup by using a concurrent hashmap.
> avoid lock contention when collecting terminals

- nomt/src/cursor.rs
- nomt/src/lib.rs
Basically, removes page prefetcher.
> seek: don't wait on page

- nomt/src/cursor.rs
Fixes https://github.com/thrumdev/nomt/pull/72#discussion_r1554441596
> fix page cursor dirty pages

- benchtop/src/main.rs
- nomt/src/lib.rs
As per discussion above, we decided to undo making session of overlay concerns.
This also pushes up the overlay logic into the only client — benchtop.
> push up overlay

- nomt/src/page_cache.rs
> fix: a deadlock in retrieve_sync

- nomt/src/cursor.rs
> fix: bug in jump

- benchtop/src/main.rs
> benchtop: better key path gen

- nomt/src/page_cache.rs
This uses a simple empty page detection algorithm to determine if a dirty page is empty and should be deleted from the underlying store.
> feat: delete empty pages from rocksdb

- core/src/update.rs
- nomt/src/lib.rs
Most of the time spent in `update` is spent in `seek`, where we unnecessarily traverse the pages. Given that the warmup workers have already done this traversal, we can replace all `seek`s with `jump`s and retrieve only a single page per edited terminal. I found this to be a substantial improvement in `update` performance.
> feat: avoid seeking in update

- core/src/page_id.rs
warmup workers spent a significant proportion of their time here.
> opt: minimize bitvec ops in page ID iterator

- nomt/src/cursor.rs
> fix: load pages only on PREFETCH_N boundary.

- core/src/proof.rs
- nomt/Cargo.toml
- nomt/src/lib.rs
- nomt/tests/add_remove.rs
- nomt/tests/common/mod.rs
- nomt/tests/witness_check.rs
I was surprised this worked without major debugging, but it works as intended.
Closes #79
> test: verify witnesses and multi-update proofs

- xtask/src/bench.rs
- xtask/src/cli.rs
- xtask/src/main.rs
- xtask/src/nomt.rs
- xtask/src/sov_db.rs
- xtask/src/transfer_workload.rs
- xtask/src/workload.rs
example of usage:
```shell
cd xtask
cargo run -- bench -b nomt,sov-db -n transfer -s 1000 -i 10
```
> bench: add transfer workload

- Cargo.lock
- core/Cargo.toml
- core/src/update.rs
pretty comprehensive test suite
> test: build_sub_trie tests

- core/src/trie_pos.rs
- nomt/src/cursor.rs
- nomt/src/page_cache.rs
this extracts the leaf data position logic, which we use to determine where to store the `LeafData`
corresponding to a particular leaf. this is in preparation for moving `seek` into a separate
`Seeker` struct.
> refactor: extract leaf data child position logic

- core/src/page_id.rs
- core/src/trie_pos.rs
- nomt/src/cursor.rs
- nomt/src/page_cache.rs
Addresses various nits from review in #137, #145, and #146
> chore: nits from 137,145,146

- benchtop/src/bench.rs
this is kind of a hacky solution, but it avoids re-initializing the database in benchtop 
for each iteration.
> refactor/benchtop: initialize only once

- benchtop/src/bench.rs
- nomt/src/page_cache.rs
- nomt/src/store.rs
ordered keys let us do this optimization in pre-fetching
> opt: use iterator to seek for pages

- nomt/src/page_cache.rs
Page fetch for nonexistent pages can sometimes take an extremely long amount of time. We often have inflight pre-fetching jobs for pages which don't exist but then need to be created during `update`. Waiting on these fetches sometimes took hundreds(!) of milliseconds on a 25k randrw workload on my device.
This extends the `hint_fresh` behavior from #151 to pre-empt inflight fetches and allocate a fresh page, anticipating the eventual result.
> opt: extend hint_fresh to pre-empt stale fetches

- nomt/src/cursor.rs
- nomt/src/page_cache.rs
- nomt/src/store.rs
The idea here is to use RocksDB [merge operators](https://github.com/facebook/rocksdb/wiki/Merge-Operator)
to avoid writing full pages when they are only slightly updated. In large commits, we update lots of pages, but many of them by only a tiny amount. However, the pages at the lowest levels of the trie are usually almost completely altered, so diffing is wasteful.
Whenever we update fewer than `FULL_PAGE_THRESHOLD=32` nodes in a page, we simply write a diff to RocksDB to be handled by the merge operator. When we update at least that many nodes, we opt to write the whole page. This parameter will require some tuning, but 32 gave good results on my end.
This eliminates most of the overhead of the WAL on pages reduces the time spent in `rocksdb_write` by about half again after #157 on my …
> opt: use rocksdb merge operator to write single nodes

- core/src/page_id.rs
- nomt/src/lib.rs
- nomt/src/page_region.rs
This implements a `PageRegion` that fulfills the requirements of the `rw_pass_cell::Region` trait.
> implement a `PageRegion` structure

- Cargo.lock
- benchtop/Cargo.lock
- nomt/Cargo.toml
- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
- nomt/src/page_cache.rs
- nomt/src/page_region.rs
- nomt/src/seek.rs
- nomt/tests/witness_check.rs
> feat: parallel update

- core/src/trie_pos.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
This adds a reasonably comprehensive test suite for the page walker, and addresses one or two 
minor bugs discovered during testing.
> test: add tests for page walker

- benchtop/src/transfer_workload.rs
This will play more nicely on a large database which is reused in multiple tests.
> refactor: select cold accounts randomly in transfer benchmark

- nomt/src/commit/mod.rs
- nomt/src/commit/worker.rs
- nomt/src/lib.rs
I envisioned two main possibilities to add the option of *not collecting a witness during commit, as described in #210. One of them could be to add a field to the options and change the `commit_and_prove` method to just `commit` and make it return an enum, with or without a witness. 
Another possibility, the one I implemented, is to avoid specifying this in the options (as it is not required) but simply add a new method to the `nomt` API, `commit`, which will return only the new root after committing everything to the database.
Tests are still missing. If the approach is okay, I will address them in a follow-up
close #210
> nomt: add commit without witness collection

- bitbox/src/beatree/leaf/node.rs
In previous PRs, the leaf encoding was changed, and cells were saved sequentially to cell_pointers. This change was ok but incomplete, which led me to suspect it was a mistake. In this state, the cell range could not properly be defined for the last value in the leaf.
Currently, the documentation describes what is implemented. If you believe it would be better to store cell_pointers and cells sequentially, we need to find another way to store the length of the values.
This also removes tests and `LeafInsertionResult`, which are not used anymore.
> fix leaf encoding

- bitbox/src/beatree/ops/update/branch.rs
- bitbox/src/beatree/ops/update/mod.rs
basically a copy of the leaf code here. stubs left over for other work
> update: core digest fn

- bitbox/src/beatree/ops/update/branch.rs
- bitbox/src/beatree/ops/update/leaf.rs
previously, this wasn't handling keys equal to the `up_to` correctly. now, we only keep when the up_to key is `None` or greater than the existing key.
> update: fix keep_up_to behavior for equal keys

- nomt/src/bitbox/beatree/mod.rs
because `File.try_clone` uses `fcntl(F_DUPFD, ..)` (https://doc.rust-lang.org/stable/src/std/os/fd/owned.rs.html#96), the FDs pocketed away in `struct Sync` were closed when `Tree::open`'s scope ended and the `File` instances went out of scope. The FDs held by the `AllocatorWriter` were different.
This fix is to just have `Sync` store the `File` instances directly and convert to raw FDs when those are needed for writeout.
> fix: improve file handling in beatree

- nomt/src/beatree/ops/update/branch.rs
- nomt/src/beatree/ops/update/leaf.rs
start was incremented too early, leading to logic errors.
> fix: increase start position at correct point in build_bulk

- nomt/src/beatree/ops/update/branch.rs
The separator override isn't really necessary for branches. We only need it for leaves, where we need a compact differentiator between the last item of the previous leaf and the first item of this leaf.
> fix: simplify separator handling in branches

- nomt/src/beatree/writeout.rs
In the BBN / LN writeout helpers, we would only attempt to submit an fsync once - at exactly the point we got the last page completion. If the queue was full, it would never be submitted again and therefore could never finish.
I observed this behavior often in the BBN routine but never in the leaf routine. I believe this is because BBN would attempt to submit the fsync while leaves were being written and clogging the io_uring worker channel. 
The fix is to adopt a `should_fsync` approach akin to what is done in the Meta helper.
> fix: stop writeout from deadlocking when fsync submission fails

- benchtop/Cargo.toml
- nomt/src/beatree/branch/mod.rs
- nomt/src/beatree/branch/node.rs
- nomt/src/beatree/ops/update/mod.rs
- nomt/src/store.rs
> hook up beatree to NOMT

- nomt/src/bitbox/mod.rs
- nomt/src/page_cache.rs
- nomt/src/store/mod.rs
Previously `commit` was probing to determine the appropriate bucket for a given page. We should never do this. We never need to probe the on-disk hash map to perform a `commit`.
Now, the page cache tracks the `BucketIndex` for a page. When a page is loaded from disk, we provide the bucket index. When a page is created afresh, we initially set the bucket index to `None`. When we write a page for the first time, we determine the bucket where the page will go at that time, simply by probing the meta map (we _know_ the page doesn't exist on disk, so we can just skip to the first empty/tombstone position in the probe sequence). When we delete a page from the store, we set the bucket index to `None`.
This also sets up my next piece of work, to change how we `get` items out of the store.
> feat: have page cache hold bucket indices

- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
pulling some common types out of the linux module and into the parent
> chore: pull some general pieces out of linux IO module

- benchtop/src/backend.rs
- benchtop/src/bench.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- nomt/src/io/linux.rs
- nomt/src/io/mod.rs
- nomt/src/io/unix.rs
- nomt/src/options.rs
- nomt/src/store/mod.rs
...and set the number of I/O threads in the non-Linux pool accordingly.
> refactor: rename num_rings to io_workers

- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
Note that the intended usage will be totally clear in future PRs. You can see that the API is well-suited for being called as part of a larger procedure that tracks the submitted page requests in e.g. a slab and applies completions.
> feat: page-loading wrapper around io handle

- nomt/src/page_cache.rs
The previous approach would have races when multiple threads all `insert`ed a page: one of the threads would be left with an orphaned page. get_or_insert semantics ensure that this cannot happen.
> fix: give PageCache::insert get or insert semantics

- nomt/src/bitbox/mod.rs
when two fresh pages wrote to an empty bucket, we were silently losing one. fixed
> fix: don't allocate two pages to same empty bucket

- nomt/src/lib.rs
- nomt/src/store/mod.rs
The store didn't actually keep the root anywhere, so new starts always had root = TERMINATOR.
This recomputes it from the root page, which is indeed kept.
> feat: compute root node from root page on startup

- nomt/src/beatree/allocator/free_list.rs
A couple bugs related to fragmentation and rewriting after pops alone were discovered.
> test: test free_list and fix discovered bugs

- nomt/src/commit/worker.rs
- nomt/src/seek.rs
This reworks the seeker's I/O loop to aggressively continue until we are blocked on submissions.
This took some reworking; we now focus only on idle requests/page loads rather than doing a sweep.
This works pretty well, and the current bottleneck seems to be the overhead of `page_loader.advance_and_replace`.
I also added an `advance_deadline` function to `Seeker`, which warm-ups use to ensure they get the "stop" signal within a reasonable amount of time.
> feat: rework new seeker to be more aggressive in pushing I/O

- nomt/src/beatree/allocator/mod.rs
- nomt/src/beatree/branch/mod.rs
- nomt/src/beatree/branch/node.rs
- nomt/src/bitbox/mod.rs
- nomt/src/io/linux.rs
- nomt/src/lib.rs
- nomt/src/page_walker.rs
- nomt/src/store/mod.rs
there are a couple concerning the WAL but I didn't want to step on @pepyakin's toes as there's a PR coming for that code soon.
> chore: address some easy and outdated TODOs

- nomt/src/beatree/allocator/mod.rs
The I/O pool is really meant for dispatching asynchronous requests, not blocking ones, and the channels add a lot of overhead to blocking requests.
On my system, where I've measured my QD1 SSD randread latency with fio to be 57us, this led to a marked improvement in state read times.
Before this PR, the mean read time was 76us. Now, it's 63us.
> opt: make raw pread syscall in AllocatorReader::query

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/mod.rs
- nomt/src/store/mod.rs
> feat: WAL recovery

- nomt/src/seek.rs
- nomt/tests/common/mod.rs
- nomt/tests/large_values.rs
> chore: squash the last warning

- nomt/src/beatree/leaf/overflow.rs
The function could be made smaller if the second condition (`needed_pages_raw_value <= MAX_OVERFLOW_CELL_NODE_POINTERS + available_page_numbers`) is removed and the latter formula is performed using f64. I didn't like casting everything to f64, so I found a way to make it work with integers
> feat: closed form for leaf overflow total_needed_pages

- nomt/src/beatree/branch/node.rs
Encode the separator and prefix length as u16
This solves the remote possibility of a branch node being encoded incorrectly because the separators do not have a shared prefix and one of them ends with a 1
> feat: branch node encoding with u16 prefix/separator lengths

- nomt/src/commit/worker.rs
Crossbeam channels can be "select"ed spuriously. This _can_ happen on linux, but seems to happen much more often on mac. Then we can end up blocking on things that don't exist.
Now we only block when there's _definitely_ an item remaining.
> fix: handle spurious Select wakeups

- nomt/src/beatree/allocator/free_list.rs
Adds types that encapsulate manipulation of a free list page.
> refactor: free list page ref & mut

- nomt/src/beatree/ops/update/leaf_stage.rs
If the changeset were smaller than `commit_concurrency`, then `prepare_worker` would end up in an infinite loop.
This also includes a modification to where the changeset is checked to be empty. It is moved from the worker to the main leaf_stage `run` function because no worker is executed without any work
> fix: leaf_stage correctly split work among workers

- nomt/src/beatree/ops/update/leaf_stage.rs
the pr contains the following changes:
+ LeafChanges entries received from the right, if contains an inserted node, will always be used as new base
Previously, if a new_entry had a bigger new_key, the base was searched through fresh leaves leading to a panic due to a double deletion of the leaf
+ `try_answer_left_neighbor` sends the right neighbor to the left one only if it has finished interacting with the right one
+ a small refactor inside `run_worker` on how the final calls to digest are handled 
+ a link to an issue related to the extension protocol
> refactor: leaf_stage range_extension handling

- nomt/src/beatree/ops/update/leaf_stage.rs
- nomt/src/beatree/ops/update/leaf_updater.rs
extend range protocol now supports also workers sharing ranges of untouched leaves
The main changes are:
- `LeafChanges` becomes `LeavesTracker` because it tracks all the changes applied to leaves and which leaves are left untouched
- `ExtendRangeResponse` can now contain not only a new base to use but also information on whether the left worker needs to use a fresh leaf and how many of them need to be skipped
I'm not a huge fan of how I ended up handling `pending_base`. It feels misplaced to keep it inside `LeavesTracker`, but any other approach I thought would end up complicating the main `run_worker` function
Note: I am working on a possible optimization that uses a Vec instead of a BTreeMap inside the LeavesTracker
> fix: extend range protocol supports ranges of untouched leaves

- nomt/src/beatree/mod.rs
Using a mutex allowed only a single thread to read from the beatree at a time, as exclusive access was gatekept during `ops::lookup`. Replacing it with an RwLock enables transaction execution parallelism.
bonus: I hit >20k TPS with `--workload-concurrency=6` on my local machine after this PR.
> refactor: use an RwLock for beatree shared state

- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/branch_updater.rs
- nomt/src/beatree/ops/update/mod.rs
The following PR mimics what is currently done by the leaf_stage in the branch_stage. The range extension protocol follows the same rules as the leaf_stage
> feat: parallel beatree branch updater

- nomt/src/beatree/ops/bit_ops.rs
average 90% improvement from `cargo bench --features benchmarks`
> opt: separate keys works on raw bytes

- nomt/src/beatree/ops/bit_ops.rs
average 90% improvement from `cargo bench --features benchmarks`
> opt: prefix_len works on raw bytes

- nomt/src/beatree/ops/bit_ops.rs
average 40% improvement from `cargo bench --features benchmarks`
> opt: separator_len works on raw bytes

- benchtop/src/cli.rs
- benchtop/src/main.rs
This is useful when testing the effect of caches, which need to be warmed up.
> feat(benchtop): add optional warm-up period

- nomt/src/commit/worker.rs
- nomt/src/page_cache.rs
- nomt/src/page_walker.rs
Maybe somewhat outdated with the follow-up PR, but this is a step towards giving workers owned page cache shards.
> opt: introduce PageCacheShard to avoid overhead

- nomt/src/seek.rs
This prevents the seeker from trying to construct an invalid `page_id` calling `next_page_id` on a `page_id` part of the last layer of the trie, which resulted in a panic in `core/src/trie_pos.rs:196`
> fix: stops seeker at last layer of the trie

- nomt/src/page_diff.rs
Anecdotally, this brought down the consumed CPU time of `WalBlobBuilder::write_update` by 50%. There is still some more room for optimization.
> opt: rewrite page diff to avoid expensive bitvec ops

- nomt/tests/last_layer_trie.rs
test change introduced in #474
> test: add last_layer_trie test

- nomt/src/bitbox/ht_file.rs
This leads to a noticeable improvement in HT write throughput, especially when the file is largely unpopulated.
> opt: preallocate HT file

- nomt/src/beatree/ops/update/tests.rs
Checking that effectively every created leaf contains all the expected values increases the execution time of the `leaf_stage` test by 1 second (on my machine). However, it really checks the correctness of the extension range protocol
> test: add existence property to leaf_stage testing

- nomt/src/io/page_pool.rs
page deallocations were expensive in a few places: page cache commit, beatree update, and lookups. by using the TLS free-list for these operations, we reduce churn.
I measured a 9% reduction in commit_and_prove time as a result of this PR.
> opt: use TLS freelist for deallocation in page pool

- nomt/src/lib.rs
- nomt/src/merkle/mod.rs
- nomt/src/page_cache.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
`PageCache::commit` has been split into two parts: `PageCache::prepare_transaction` and `PageCache::evict`.
This previously ran prior to sync and took a large portion of sync time, during which the disk was idle. Now, this runs in parallel with beatree's prepare_sync, and eviction has been moved out of the critical path altogether.
I measured a workload which took 310ms for `commit_and_prove` as of the parent commit. It's now down to 255ms, saving 55ms on average (which was typically what samply showed for the time of `PageCache::commit`).
In the same workload, the disk is now idle only during beatree `prepare_sync`. With future optimizations and interleaving, that gap should also disappear entirely.
> opt: run page-cache commit and eviction on sync threadpool

- benchtop/src/nomt.rs
Cleans up a build error after https://github.com/thrumdev/nomt/pull/512
> fix: fix benchtop build

- .github/workflows/ci.yml
Adds a github actions job to verify that benchtop builds without issues.
> chore: build benchtop in CI

- nomt/src/bitbox/meta_map.rs
- nomt/src/bitbox/mod.rs
> refactor: track occupied buckets in bitbox DB

- nomt/src/merkle/mod.rs
Previously, `join()` would collect the outputs of workers in spawning order as opposed to finishing order. That meant that a slow worker would delay some CPU load to the critical path (usually a few milliseconds).
Now, workers send their results over a single channel, so `join` processes them as workers finish.
It's a small optimization, but a very low hanging fruit.
> opt: collect merkle update worker outputs in finishing order

- nomt/src/beatree/allocator/free_list.rs
- nomt/src/beatree/allocator/mod.rs
Calling `pop()` in a loop had the potential to be expensive. The new `fn discard` achieves the same result.
With our architecture, it's not possible to do this in O(1) time, but we can make the constant factor much smaller. 
With a new loop focused on free-list segments, even `discard(100_000)` will only require about 100 loop iterations.
> refactor: introduce FreeList::discard for fast resizing

- nomt/src/beatree/ops/update/branch_stage.rs
- nomt/src/beatree/ops/update/mod.rs
The main purpose here is to improve the encapsulation of the branch stage to its own module.
However, this'll also serve as a small optimization of a couple milliseconds. Rather than collecting all the changes into a bigger BTreeMap and iterating it at the end, we can remove some CPU load from the critical path.
I had to comment out the update quickcheck tests for a moment and will fix them after this stack is completed.
> refactor(branch-stage): apply BBN stages as workers finish

- nomt/src/beatree/ops/update/leaf_updater.rs
A few purposes:
1. I'm working on the feature to submit I/O as leaves/branches are created. Therefore this trait will be used in a future PR to both submit I/O and insert into the tracker.
1. LeavesTracker is a higher level piece of logic, and the updater benefits from being separated from it.
> refactor(beatree): remove hard dependency on LeavesTracker in updater

- nomt/src/beatree/ops/update/branch_updater.rs
Same logic as the preceeding leaves PR, but for branches.
> refactor(beatree): remove hard dependency on BranchesTracker in updater

- .github/workflows/bench.yml
> chore: try to run benchtop

- nomt/src/io/unix.rs
> chore: remove unused MAX_IN_FLIGHT

- core/src/page_id.rs
We spend a lot of time encoding Page IDs. 
Most Page IDs (any which are above a 64-byte collision) are short.
> opt: fast-path for PageId::encode

- nomt/src/io/fsyncer.rs
- nomt/src/io/mod.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
one of the steps towards THR-33.
> chore: fsyncer

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/tests.rs
- nomt/src/bitbox/wal/write.rs
- nomt/src/bitbox/writeout.rs
- nomt/src/store/mod.rs
- nomt/src/store/page_loader.rs
- nomt/src/store/sync.rs
No functional changes.
Similar to #576
Closes THR-40
> chore: tuck bitbox sync

- nomt/src/beatree/mod.rs
- nomt/src/bitbox/mod.rs
specifically, reuse the threadpool between the runs of sync.
this also locks beatree for the entire duration of sync.
> cleanup beatree & bitbox

- nomt/src/rollback/mod.rs
- nomt/src/store/sync.rs
This is the last commit on my quest of splitting up the sync module and isolating each individual component.
Closes THR-33
> chore: tuck rollback sync

- nomt/src/store/mod.rs
tmpfs doesn't support O_DIRECT so avoid using that.
> fix: avoid o_direct on tmpfs

- nomt/src/merkle/mod.rs
- nomt/src/merkle/worker.rs
instead, bubble them up in the loop. This still requires
a better error handling approach.
> fix: dont swallow merkle update worker errors

- nomt/src/merkle/page_walker.rs
- nomt/src/page_diff.rs
Sometimes, a page was properly created by the PageWalker, but then in subsequent commits an empty page was found.
For this to occur, two conditions needed to be satisfied:
1. A leaf must have been placed at the last level of a page, resulting in children in the next page.
For example, a value with a key of 0b00000001_00000000_... which currently resides at the 6th level of the first page.
2. A new leaf with a common prefix of at least 15 bits needed to be introduced.
For instance, 0b00000001_00000001_...
During the update, a new subtree would be created below the existing leaf, involving the following steps:
1. Clearing the children of the existing leaf (setting the 'cleared' bit to 1 in the relative page_diff)
2. Establishing a new page to store both leaves and their children
3. Writing …
> fix: update clear bit in page_diff

- nomt/src/beatree/leaf/overflow.rs
I wrote this to quickly verify the correctness of a previous PR. Decided that I might as well submit those.
> test: add proptests for overflow cell serde

- nomt/src/merkle/page_walker.rs
- nomt/src/page_diff.rs
> test: add page_diff clear bit related tests

- nomt/src/beatree/mod.rs
- nomt/src/beatree/ops/mod.rs
This adds a lookup function for async reads using the beatree `ReadTransaction`.
Loads of overflow values still block; this will be fixed in a follow-up.
> refactor: expose lookup_async from beatree ReadTransaction

- nomt/src/beatree/ops/overflow.rs
This isn't used (in this PR) but can be used in:
1. (immediately) rollback to avoid blocking on overflow values
2. (later) any asynchronous session stuff we add later.
> feat(beatree): add an asynchronous overflow value fetcher

- nomt/src/beatree/ops/update/branch_ops.rs
- nomt/src/beatree/ops/update/branch_updater.rs
Also update a vestigial with the correct name of the test.
> fix: use `gauge.body_size/2` as target in try_split

- benchtop/src/backend.rs
- benchtop/src/cli.rs
- benchtop/src/main.rs
- benchtop/src/nomt.rs
- nomt/src/options.rs
- nomt/src/page_cache.rs
> feat: make `page_cache_size` a nomt option

- nomt/src/beatree/ops/update/leaf_updater.rs
mimic the refactor done in BranchUpdater
> refactor: add `try_build_leaves` in LeafUpdater

- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/comms.rs
Thanks @gabriele-0201 for a lead.
> torture: increase frame size

- nomt/src/store/mod.rs
The lock previously was taken after creating the database files. Actually it's
important to take the lock before performing any changes to the directory.
Otherwise it can lead to a race between the two processing messing each others
files.
This commit fixes that.
> fix: flock asap db dir on create

- torture/src/supervisor/workload.rs
use indicies instead of keys verbatim. This might be useful
for the big key spaces.
> torture: use more compact repr for keys

- Cargo.lock
- torture/Cargo.toml
- torture/src/supervisor.rs
- torture/src/supervisor/cli.rs
Add basic CLI arguments parsing and make the seed
configurable. If not specified generate it randomly.
> torture: cli parse & seed

- nomt/src/beatree/allocator/free_list.rs
It is possible to collect a `PageNumber` while decoding the FreeList, which is out of the bounds of the file, leading to the `io` module writing to possibly absurd addresses. Currently, the unix module uses `pwrite`, which extends the file if the offset happens to be bigger than the file size, the same for io_uring+iopoll+o_direct used in the `linux` module. To protect against this, a simple check is being added to ensure that each `PageNumber` read from the free list is contained within the bounds of the file itself.
> feat: tighten read of freelist recover

- nomt/tests/fill_and_empty.rs
make fill_and_empty reproducible and effectively
write and read all generated keys
> test: fix fill_and_empty tests

- torture/src/agent.rs
this is important not to monopolize the thread. This is not usually an issue because the tokio runtime has more than one thread, but it's better be safe than sorry.
> fix(torture): spawn commit as blocking

- nomt/src/merkle/seek.rs
- nomt/src/overlay.rs
Adds iteration capabilities to the overlay, and uses that to get leaf preimages during merklization.
> feat: use overlay for leaf preimages in merklization

- nomt/src/beatree/allocator/free_list.rs
In `FreeList::commit` if we popped but didn't push items onto the free-list, we were not setting self.pop to false. This caused an assertion to fail in the next commit.
> fix: free-list commit always sets 'pop' to false

- torture/src/logging.rs
- torture/src/supervisor/cli.rs
- torture/src/supervisor/mod.rs
update some old `orture` vestigials and remove all `workload-`s
prefix in the cli
> chore(torture): update some names

- torture/src/supervisor/mod.rs
Let the first execution of a workload use the master seed,
continue increasing it by one for each workload execution,
and print the seed used to execute the workload if it fails.
> chore(torture): update master seed usage

- torture/src/supervisor/mod.rs
Also drive-by chore adding comment to seed.
> fix(torture): fix indent when printing flag

- nomt/src/beatree/ops/bit_ops.rs
`bitwise_memcpy` must ensure that all bits which are not involved in the
copy are left unchanged. All bits before `destination_bit_start` and all
bits after `destination_bit_start + source_bit_len`.
Other minor fixes are also present, making the doc clearer about the
function's requirements and updating the name of a variable to be
logically correct.
> fix: leave untouched bits in destination unchanged

- torture/src/supervisor/workload.rs
Instead of storing a series of snapshots and performing a rollback once in a while,
randomly schedule a rollback or a rollback crash,
and only save the state to which we are going to rollback to.
This is based on what @pepyakin suggested [here](https://github.com/thrumdev/nomt/pull/706#discussion_r1922504208)
> refactor(torture): allow long rollback tests

- nomt/src/beatree/ops/update/leaf_stage.rs
Within this [action](https://github.com/thrumdev/nomt/actions/runs/12996378074/job/36245038318) the leaf stage test was hanging, a panic was found but the input was not printed. This issue is not due to `quickcheck` because no-shrink on CI works. The problem lies within the leaf stage itself. In the leaf stage, a thread pool is used to spawn the leaf stage worker, which sends the output upon completion. The main thread then waits for a response on the channel provided to the worker to get the result. If a task spawned within the thread pool panics , apparently , it doesn't drop the channel, thus failing to signal to the main thread that an error occurred, causing it to wait indefinitely.
To address this issue, simply send the error through the channel.
There is one minor issue, though: …
> fix: do not hang if leaf_stage panics

- torture/src/agent.rs
At this time, upon abort an identical message printed for both rollback
and commit. This changeset adds the origin of the abort.
> feat(torture): print abort reason

- nomt/src/merkle/mod.rs
address https://github.com/thrumdev/nomt/pull/749#discussion_r1931919573
> chore: add comment on merkle::BucketInfo

- trickfs/src/lib.rs
So far, this is the fs-wide flag that when turned on will reject all
writes (and even fsync) returning the ENOSPC errors.
> feat(trickfs): trickfs now can signal ENOSPC

- nomt/src/bitbox/mod.rs
- nomt/src/store/mod.rs
- nomt/src/store/sync.rs
Instead just poison.
Fixes THR-76
> fix: do not panic when hash-table is full

- nomt/src/rollback/mod.rs
- nomt/src/rollback/tests.rs
- nomt/src/seglog/mod.rs
Follow up on #795 and what was suggested [here](https://github.com/thrumdev/nomt/pull/795#pullrequestreview-2605310128)
> refactor,tests: rollback writeout start and end

- nomt/src/io/linux.rs
> fix: handle EINTR in io_uring_enter

- torture/src/spawn.rs
tokio's unixstream is expected to be non-blocking. To quote the
[doc]:
The caller is responsible for ensuring that the stream is in
non-blocking mode. Otherwise all I/O operations on the stream
will block the thread, which will cause unexpected behavior.
Non-blocking mode can be set using set_nonblocking.
And oh boy we were observing unexpected behavior. One is that
because of blocking of the thread polling some tokio worker thread we
had problems with receiving from a oneshot channel which required some
nasty workaround (fix is going to follow later on). Another problem this
caused is a deadlock of both the supervisor and the agent when the
former was waiting on the LLDB taking the backtrace of the agent. LLDB
for unresearched reason was hanging itself.
This changeset should finally fix …
> fix(torture): mark comms stream non-blocking

- nomt/src/store/mod.rs
it might be useful to open nomt in temporary folder. 
Of course it can be solved on user end by appending "nomt" as path inside newly created temp directory, but I think it is slightly better dev-ex
> Suggestion: Allow to open nomt in a new empty directory

- Cargo.lock
- torture/Cargo.toml
- torture/src/agent.rs
- torture/src/message.rs
- torture/src/supervisor/comms.rs
- torture/src/supervisor/config.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/mod.rs
- torture/src/supervisor/swarm.rs
- torture/src/supervisor/workload.rs
Add Swarm Testing. Instead of using cli arguments, a variety of features are now utilized or omitted to create workload configurations. These configurations are then used to open and execute workloads.
Workloads are executed in parallel to maximize the usage of the available resources.
> feat(torture): swarm testing

- Cargo.lock
- torture/Cargo.toml
- torture/src/agent.rs
- torture/src/message.rs
- torture/src/spawn.rs
- torture/src/supervisor/cli.rs
- torture/src/supervisor/comms.rs
- torture/src/supervisor/config.rs
- torture/src/supervisor/controller.rs
- torture/src/supervisor/mod.rs
- torture/src/supervisor/swarm.rs
- torture/src/supervisor/workload.rs
Redirect agent stdout and stderr to `log.txt`.
> feat(torture): agent redirect stdout and stderr

- Cargo.toml
- core/Cargo.toml
- fuzz/Cargo.toml
- nomt/Cargo.toml
- torture/Cargo.toml
- trickfs/Cargo.toml
Embrace { workspace = true } everywhere.
> chore: move deps to workspace

- Cargo.lock
- Cargo.toml
- benchtop/Cargo.lock
- core/Cargo.toml
- core/src/proof/path_proof.rs
- core/src/trie.rs
- core/src/trie_pos.rs
- nomt/Cargo.toml
- nomt/src/lib.rs
Allow to serialize witness using serde
> Serde support for Witness

- nomt/src/bitbox/mod.rs
- nomt/src/bitbox/wal/read.rs
- nomt/src/bitbox/wal/tests.rs
- nomt/src/bitbox/wal/write.rs
- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/merkle/seek.rs
- nomt/src/page_cache.rs
Follow up https://github.com/thrumdev/nomt/pull/861#discussion_r2037947943
> refactor: use `ElidedChildren` struct everywhere

- torture/src/supervisor/workload.rs
Set the `max_crash_delay` to be smaller than the tolerance, otherwise,
the agent could be forced to crash just after the tolerance deadline,
leading to `agent did not die`. It also includes an updated comment, follow up https://github.com/thrumdev/nomt/pull/862#discussion_r2039042482.
> fix(torture): avoid `agent did not die`

- core/src/proof/path_proof.rs
- nomt/tests/witness_check.rs
It may happen that there are no shared bits because the paths are empty.
In that case, there is going to be an underflow.
UPD: turned out my initial fix is not sufficient, so posting here only the failing test with an intent to update it later.
UPD: Solved this by moving the preconditions check into a single pass before running any logic.
> fix: verify_update overflow fix

- core/src/proof/multi_proof.rs
- nomt/src/beatree/ops/update/extend_range_protocol.rs
hey team! I found duplicate words and fixed them.
> docs: remove consecutive duplicate words

- nomt/src/merkle/mod.rs
- nomt/src/merkle/page_set.rs
- nomt/src/merkle/page_walker.rs
- nomt/src/page_diff.rs
Follow ups to multiple wrong or inaccurate comments
> docs: update multiple comments

- core/src/proof/multi_proof.rs
> fix: empty multiproof creation no longer panics

- nomt/src/beatree/ops/update/branch_ops.rs
Within the function `extract_ops_until`, there were some edge cases
where a key with a completely different prefix from the others caused
the size of the encoding to increase from around the merge threshold,
exceeding the branch node size.
This commit decrease the target not only if the bump was from below
the threshold but also if it was above, to avoid the need to
use `stop_prefix_compression` and having a gauge properly updated.
This fixes the bug shown in #898
> fix: reduce branch node target during ops collection

- core/src/proof/multi_proof.rs
- core/src/witness.rs
> Add comments about path-proof sorting guarantees and requirements

- nomt/src/merkle/seek.rs
Closes #902 
@omerb4n - this fixed both of the test cases you provided. let me know if there are any others to try.
> Handle overlay deletions in seek/page elision correctly
